python-zeroconf/python-zeroconf

zeroconf.py
On my windows machine, I see a few "disconnected" network interfaces (VPN tunnel, Virtual box tunnel, disconnected LAN interface). However, these interfaces do get an ip address in the range 169.254.x.x from windows.
However, when starting zeroconf, the code cannot add these to the multicast group. And you get an EADDRNOTAVAIL error.
This patch handles the error and continues properly by adding the rest of the "real" network interfaces.
=> Handle EADDRNOTAVAIL error when adding multicast groups (for windows)

zeroconf.py
Prevents following exception in Python 3:
```
File "/Users/paulus/dev/python/netdisco/lib/python3.4/site-packages/zeroconf.py", line 412, in __repr__
return self.to_string(self.text[:7] + "...")
TypeError: can't concat bytes to str
```
=> Fix DNSText repr Python 3 issue

zeroconf.py
`IP_MULTICAST_TTL` and `IP_MULTICAST_LOOP` socket options on OpenBSD don't accept int, only `unsigned char`.
This causes a kernel error when these options are set: `socket.error: [Errno 22] Invalid argument`.
According to the OpenBSD's [ip(4)](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man4/ip.4?query=ip) man page, these fields are both `unsigned char`:
>u_char ttl;     /* range: 0 to 255, default = 1 */
>setsockopt(s, IPPROTO_IP, IP_MULTICAST_TTL, &ttl, sizeof(ttl));
>
>u_char loop;	/* 0 = disable, 1 = enable (default) */
>setsockopt(s, IPPROTO_IP, IP_MULTICAST_LOOP, &loop, sizeof(loop));
This patch was tested successfully on Linux (Ubuntu 14.04), FreeBSD 10.2 and OpenBSD 5.8 using Python 2.7, 3.4, 3.5.
=> Fix multicast TTL and LOOP options on OpenBSD

setup.py
Installing using pip resulted in error:
```
Collecting git+https://github.com/jstasiak/python-zeroconf
Cloning https://github.com/jstasiak/python-zeroconf to /tmp/pip-f2knhtr9-build
Complete output from command python setup.py egg_info:
File "<string>", line 20, in <module>
File "/tmp/pip-f2knhtr9-build/setup.py", line 10, in <module>
readme = f.read()
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4280: ordinal not in range(128)
```
This PR fixes the encoding in Python 3.5 and is also backported to support 2.6+
=> Installation python3.5

.gitignore, setup.cfg, test_zeroconf.py, zeroconf.py
When querying for a service type, the response is processed.  During the
processing, an info lookup is performed.  If the info is not found in
the cache, then a query is sent.  Trouble is that the info requested is
present in the same packet that triggered the lookup, and a query is not
necessary.  But two problems caused the cache lookup to fail.
1) The info was not yet in the cache.  The call back was fired before
all answers in the packet were cached.
2) The test for a cache hit did not work, because the cache hit test
uses a DNSEntry as the comparison object.  But some of the objects in
the cache are descendents of DNSEntry and have their own \__eq__()
defined which accesses fields only present on the descendent.  Thus the
test can NEVER work since the descendent's \__eq__() will be …
=> Multiple fixes to speed up querys and remove exceptions at shutdown

test_zeroconf.py, zeroconf.py
This fixes a regression from removal of some overly broad exception
handling in 0.17.6.  This change adds an explicit handler for
DNSIncoming().  Will also log at warn level the first time it sees a
particular parsing exception.
Also make all test cases localhost only.
This addresses #63 and #65
=> Handle DNSIncoming exceptions

README.rst, setup.py, test_zeroconf.py, zeroconf.py
This addresses issue #29.  It fixes / implements auto name changing for service advertisement when the service name is already present on the network.
In addition some documentation for DNS Additional Record Generation is added.
=> Fix name change

test_zeroconf.py, zeroconf.py
Add new records first in cache entry to make DNSCache.get return the newest record instead of the oldest.
This means updates, for example IP address changes, do not need to wait for expiry of old records.
=> Add new records first in cache entry instead of last

zeroconf.py
As described in https://github.com/jstasiak/python-zeroconf/issues/122
=> add import error for Python <= 3.3

test_zeroconf.py, zeroconf.py
Honor TTL passed in service registration
Set default TTL to 120 s as recommended by RFC6762
=> Fix TTL handling for published service, align default TTL with RFC6762

.travis.yml, requirements-dev.txt, setup.py, test_zeroconf.py, zeroconf.py
This makes flake8 happy so the build can pass again.
The reason I added `flake8 --version` to the tests is because my version of flake8 expects the imports in a different order.
This way I could install the same version as you and therefore make sure everything passes.
`pep8-naming` in particular is crashing on version `0.6.0` so I had to black list it.
That's a trick I learned from the author of `catt`
=> Fix flake8

zeroconf.py
This code throws an `UnboundLocalError` as `count` doesn't exist in the `else` branch of the for loop. The else branch happens if the break condition is never met, therefore the equivalent (and more straightforward/less clever) statement is to set it to `len(name_suffices)`.
=> Fix UnboundLocalError for count after loop

setup.py, zeroconf.py
The latest release of zeroconf in PyPI (0.21.0) breaks compatibility with python 3.4 due to an unstated dependency on the ``typing`` package. This patch adds that dependency and issues a new minor version of zeroconf.
=> Bringing back compatibility with python 3.4

.travis.yml
The latest currently easily available on Travis.
(Build failure is unrelated, fixed by #147.)
=> Test with PyPy 3.5 5.10.1

test_zeroconf.py, zeroconf.py
This request targets a modification of the default value of the argument `properties` of `ServiceInfo`'s `__init__()`. The default value on the current commit (51a6f70) is `None`. The suggested modification changes this value to `b''`.
Looking at the code, if `properties` is a dictionary, the function `_set_properties()` will create a byte array with the user's properties; if properties is a byte array, it just sets the property. As it is, an because `properties` is not mandatory, if a user does not specify the argument, an exception (`AssertionError`) is thrown. Changing the default value to a byte array, which avoids the conversion to byte array, solves this problem. With this modification, it is possible to instantiate ServiceInfo on the following three ways - the last is not possible …
=> Modified ServiceInfo's __init__ properties' default value.

test_zeroconf.py, zeroconf.py
This resolves a bug in the shutdown behaviour which fails to send out service removals if services haven't been explicitly removed before a call to `close()`.
=> Fix service removal packets not being sent on shutdown

test_zeroconf.py, zeroconf.py
This PR aims to bring the default TTLs for DNS record types into line with RFC 6762.
Whilst there are two default TTLs dependent on the record type, there is only one argument to `register_service`, so I've tried to maintain the existing behaviour to avoid breaking the interface. If it is seen as useful or important to be able to set these TTLs independently then the final commit adds new arguments to the `ServiceInfo` constructor for this purpose. I'd be happy to remove the final commit if there isn't seen to be a great deal of value in that flexibility.
I hope this is useful, and I'd be interested in any feedback on the approach.
=> Match default TTLs to those specified in RFC 6762

Makefile
Otherwise black tries to check the "env" directory, which fails.
=> Makefile: be specific which files to check with black

examples/browser.py, examples/registration.py, examples/self_test.py, test_zeroconf.py, zeroconf.py
This is a rebased and fixed version of PR #27, which also adds compatibility shim for ServiceInfo.address and does a proper deprecation for it.
=> Add support for multiple addresses when publishing a service

.travis.yml, Makefile, README.rst, examples/browser.py, examples/registration.py, test_zeroconf.py, zeroconf.py
This change adds basic support for listening on IPv6 interfaces.
Some limitations exist for non-POSIX platforms, pending fixes in
Python and in the ifaddr library. Also dual V4-V6 sockets may not
work on all BSD platforms. As a result, V4-only is used by default.
=> First stab at supporting listening on IPv6 interfaces

test_zeroconf.py, zeroconf.py
RFC6763 indicates a server should include the SRV/TXT/A/AAAA records
when responding to a PTR record request.  This optimization ensures
the client doesn't have to then query for these additional records.
It has been observed that when multiple Windows 10 machines are monitoring
for the same service, this unoptimized response to the PTR record
request can cause extremely high CPU usage in both the DHCP Client
& Device Association service (I suspect due to all clients having to
then sending/receiving the additional queries/responses).
=> Add additional recommended records to PTR responses

examples/self_test.py, test_zeroconf.py, zeroconf.py
This PR incorporates changes from the earlier PR #179 (thanks to Mikael Pahmp), adding tests and a few more fixes to make AAAA records work in practice.
Note that changing `addresses` to container IPv6 addresses may be considered a breaking change, for example, for consumers that unconditionally apply `inet_aton` to them. I'm introducing a new function to be able to retries only addresses from one family.
=> Make AAAA records work (closes #52)

test_zeroconf.py, zeroconf.py
The correct record type was missing in a few places. Also use
addresses_by_version(All) in preparation for switching addresses
to V4 by default.
=> Finish AAAA records support

examples/self_test.py, test_zeroconf.py, zeroconf.py
* Return backward compatibility for ServiceInfo.addresses by making
it return V4 addresses only
* Add ServiceInfo.parsed_addresses for convenient access to addresses
* Raise TypeError if addresses are not provided as bytes (otherwise
an ugly assertion error is raised when sending)
* Add more IPv6 unit tests
=> Rework exposing IPv6 addresses on ServiceInfo

zeroconf.py
When `python-zeroconf` is used in conjunction with `eventlet`, `select.select()` will return with an error code equal to `errno.ENOTCONN` instead of `errno.EBADF`. As a consequence, an exception is shown in the console during shutdown. I believe that it should not cause any harm to treat `errno.ENOTCONN` the same way as `errno.EBADF` to prevent this exception.
As a reference, here is the exception traceback that I get on macOS without the patch after calling `close()` on the `Zeroconf` object:
```
Exception in thread zeroconf-Engine:
File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/Users/tamas/.local/share/virtualenvs/flockwave-server-gJJc3Vqn/lib/pyt …
```
=> ENOTCONN is not an error during shutdown

zeroconf/__init__.py, zeroconf/test.py
Previously the reset_ttl method changed the time created and the TTL value, but did not change the expiration time or stale times. As a result a record would expire even when this method had been called.
=> Fix resetting of TTL

zeroconf/__init__.py, zeroconf/test.py
Fixes issues with shared records being used where they shouldn't be.
PTR records should be shared, but SRV, TXT and A/AAAA records should be unique.
Whilst mDNS and DNS-SD in theory support shared records for these types of record, they are not implemented in python-zeroconf at the moment.
See zeroconf.check_service() method which verifies the service is unique on the network before registering.
=> Class Unique fix

zeroconf/__init__.py
Host-only netmasks do not forbid multicast.
Tested on Debian 10 running in Qubes and on Ubuntu 18.04.
Fixes #221.
=> Do not exclude interfaces with host-only netmasks from InterfaceChoice.All

zeroconf/__init__.py, zeroconf/test.py
This PR fixes the representation of DNSAddress instances that have an IPv6 address. Previously, the repr of such instances would contain a string of the packed bytearray. 
This is mostly a cosmetic change. It replaces the last occurrence of `socket.ntoa()` with `socket.ntop()`.
=> Fix representation of IPv6 DNSAddress

zeroconf/__init__.py, zeroconf/test.py
The prior code used to send updates even when the new record was identical to the old.
This resulted in duplicate update messages when there was in fact no update (apart from TTL refresh)
=> Duplicate updates fix

zeroconf/__init__.py, zeroconf/test.py
It's been wrong since the first commit. Empty strings are just empty strings.
=> Do not convert empty strings in TXT records to bool

zeroconf/__init__.py
The assertions, added in [1] and modified in [2] introduced a
regression. When browsing in the presence of devices advertising SRV
records not marked as unique there would be an undesired crash (from [3]):
Exception in thread zeroconf-ServiceBrowser__hap._tcp.local.:
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/home/pi/homekit-debugging/venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 1504, in run
handler(self.zc)
File "/home/pi/homekit-debugging/venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 1444, in <lambda>
zeroconf=zeroconf, service_type=self.type, name=name, state_change=state_change
File "/home/pi/homekit-debugging/venv/lib/python3.7/site-packages/zeroconf/__init__.py", line 1322, …
=> Remove uniqueness assertions

.travis.yml, Makefile, requirements-dev.txt, zeroconf/test.py
Nose is dead for all intents and purposes (last release in 2015) and
pytest provide a very valuable feature of printing relevant extra
information in case of assertion failure (from[1]):
================================= FAILURES =================================
_______________________________ test_answer ________________________________
def test_answer():
>       assert func(3) == 5
E       assert 4 == 5
E        +  where 4 = func(3)
test_sample.py:6: AssertionError
========================= short test summary info ==========================
FAILED test_sample.py::test_answer - assert 4 == 5
============================ 1 failed in 0.12s =============================
This should be helpful in debugging tests intermittently failing on
PyPy.
Several TestCase.assertEqual() calls have been …
=> Switch to pytest for test running

zeroconf/test.py
Finally found the reason for the unstable failing test that has been bugging me for months!
Travis doesn't support IPv6, at least not stably, but there were still some tests that used some of the features that were failing intermittently.
=> remove unstable IPv6 tests from travis

zeroconf/__init__.py
Update `Engine` such that the thread is immediately notified. This gets rid of the 5s hang on `Zeroconf.close()`.
=> Update Engine to immediately notify its worker thread

setup.py
The CI was hitting on the `l` variable per
https://www.flake8rules.com/rules/E741.html
=> Fix flake8 E741 in setup.py

setup.py, zeroconf/__init__.py
Reported to Home Assistant here
https://github.com/home-assistant/core/issues/35832
I was able to replicate with ~200 restarts.
Fixes
```
Exception in thread zeroconf-Engine:
File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1228, in run
reader.handle_read(socket_)
File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1301, in handle_read
self.zc.handle_response(msg)
File "/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py", line 2501, in handle_response
with self._handlers_lock:
AttributeError: 'Zeroconf' object has no attribute '_handlers_lock'
```
=> Fix race condition where a listener gets a message before the lock is created.

examples/browser.py, setup.py, zeroconf/__init__.py, zeroconf/test.py
As each ServiceBrowser runs in its own thread there
is a scale problem when listening for many types.
I've tried to do this in a way that provides backwards compatibility. 
All of the existing tests pass.
ServiceBrowser can now accept a list of types
in addition to a single type.
As Home Assistant adds more discoverable services this
problem continues to grow
https://github.com/home-assistant/core/blob/dev/homeassistant/components/zeroconf/__init__.py#L213
=> Add support for multiple types to ServiceBrowsers

zeroconf/__init__.py
Integers aren't guaranteed to have the same identity even though they
may be equal.
=> Use equality comparison instead of identity comparison for ints

zeroconf/__init__.py
Give threads unique names to improve log clarity when there are multiple zeroconf instances or multiple service browsers for the same type.
=> Give threads unique names

zeroconf/__init__.py
Don't hold `_handlers_lock` when calling the service callbacks.
Closes #255 
Background:
#239 adds the lock `_handlers_lock`:
https://github.com/jstasiak/python-zeroconf/blob/552a030eb592a0c07feaa7a01ece1464da4b1d0b/zeroconf/__init__.py#L2209
Which is used in the engine thread:
https://github.com/jstasiak/python-zeroconf/blob/552a030eb592a0c07feaa7a01ece1464da4b1d0b/zeroconf/__init__.py#L2484-L2489
And also by the service browser when issuing the state change callbacks:
https://github.com/jstasiak/python-zeroconf/blob/552a030eb592a0c07feaa7a01ece1464da4b1d0b/zeroconf/__init__.py#L1541-L1546
Both pychromecast and Home Assistant calls `Zeroconf.get_service_info` from the service callbacks which means the lock may be held for several seconds which will starve the engine thread.
=> Don't call callbacks whend holding _handlers_lock

zeroconf/__init__.py
This is in order to provide visibility to the library users that this method exists - without it the client code may be missing data.
=> Warn on every call to missing update_service() listener method

setup.py
We don't support Python older than 3.5.
=> Remove no longer needed typing dependency

zeroconf/__init__.py
when there is nothing to write, we don't need to warn about not making progress.
=> Fixed false logging warning

zeroconf/__init__.py
Windows reports errno.WSAEINVAL(10022) instead of errno.EINVAL(22).
This fixes #189
I create a second IP under windows by switching to static ip and assigning two IP's (
http://woshub.com/assign-multiple-ip-addresses-single-nic-windows/ ). I then test using:
```
python -c "from zeroconf import ZeroconfServiceTypes; print('\n'.join(ZeroconfServiceTypes.find()))"
```
from windows.
=> zeroconf support windows when using socket errno checks

zeroconf/__init__.py, zeroconf/test.py
Not sure if parsed_addresses is the best way to name the parameter, but
we already have a parsed_addresses property so for the sake of
consistency let's stick to that.
=> Add support for passing text addresses to ServiceInfo

zeroconf/__init__.py
Otherwise it'd complain:
% make mypy
mypy examples/*.py zeroconf/*.py
zeroconf/__init__.py:2039: error: Returning Any from function declared to return "int"
Found 1 error in 1 file (checked 6 source files)
make: *** [mypy] Error 1
=> Make Mypy happy

zeroconf/__init__.py, zeroconf/test.py
Sorry I missed this in the original submission #249. 🙊 
When creating listeners for a ServiceBrowser with multiple types
they would not all be removed on cancelation. This led
to a build up of stale listeners when ServiceBrowsers were
frequently added and removed.
=> Ensure all listeners are cleaned up on ServiceBrowser cancelation

zeroconf/__init__.py
As discussed here: https://github.com/jstasiak/python-zeroconf/pull/292#discussion_r471787269
=> Remove initial delay before querying for service info

zeroconf/__init__.py, zeroconf/test.py
Avoid copying the entires cache and reduce frequency of Reaper
The cache reaper was running at least every 10 seconds, making
a copy of the cache, and iterated all the entries to
check if they were expired so they could be removed.
In practice the reaper was actually running much more frequently
because it used self.zc.wait which would unblock any time
a record was updated, a listener was added, or when a
listener was removed.
This change ensures the reaper frequency is only every 10s, and
will first attempt to iterate the cache before falling back to
making a copy.
Previously it made sense to expire the cache more frequently
because we had places were we frequently had to enumerate
all the cache entries. With #247 and #232 we no longer
have to account for this concern.
On a mostly idle …
=> Reduce frequency of Reaper and avoid copying the cache when possible

zeroconf/__init__.py
This screenshot explains what I'm seeing as a client. The `ServiceBrowser` type hints the listener as an `Optional[ServiceListener]` but trying to import `ServiceListener` gives a warning since it's not explicitly included in the `__all__` of Zeroconf's module.
=> Add ServiceListener to __all__ for Zeroconf module

.travis.yml
There've been reports of test failures on Python 3.9, let's verify this.
Allowing failures for now until it goes stable.
=> Test with Python 3.9

zeroconf/__init__.py
When watching packet captures, I noticed that zeroconf was processing
incoming data 3x on a my Home Assistant OS install because there are
three interfaces.
We can skip processing duplicate packets in order to reduce the overhead
of decoding data we have already processed.
`strace -p 231 -f -s 4096 -e trace=recvfrom`
```
[pid   267] recvfrom(7, "\224\7\0\0\0\1\0\0\0\0\0\0\17_home-assistant\4_tcp\5local\0\0\f\0\1", 8966, 0, {sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("172.30.32.3")}, [16]) = 44
[pid   267] recvfrom(7, "\224\7\0\0\0\1\0\0\0\0\0\0\17_home-assistant\4_tcp\5local\0\0\f\0\1", 8966, 0, {sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("192.168.213.154")}, [16]) = 44
[pid   267] recvfrom(9, "\224\7\0\0\0\1\0\0\0\0\0\0\17_home-assistant\4_tcp\5local\0\0\ …
```
=> Avoid processing duplicate packets

zeroconf/test.py
We only had module-level unittest import before now, but code accessing
mock through unittest.mock was working because we have a test-level
import from unittest.mock which causes unittest to gain the mock
attribute and if the test was run before other tests (those using
unittest.mock.patch) all was good. If the test was not run before them,
though, they'd fail.
Closes GH-295.
=> Fix AttributeError: module 'unittest' has no attribute 'mock'

zeroconf/__init__.py, zeroconf/test.py
Validation of names was too strict and rejected devices that are otherwise
functional.  A partial list of devices that unexpectedly triggered
a BadTypeInNameException:
Bose Soundtouch
Yeelights
Rachio Sprinklers
iDevices
Fixes: https://github.com/home-assistant/core/issues/39116, https://github.com/home-assistant/core/issues/38914, https://github.com/home-assistant/core/issues/33085, https://github.com/home-assistant/core/issues/31262, https://github.com/home-assistant/core/issues/41355
=> Loosen validation to ensure get_service_info can handle production devices

examples/browser.py
Before this change, script `examples/browser.py` printed IPv4 only, even with `--v6` argument.
With this change, `examples/browser.py` prints both IPv4 + IPv6 by default, and IPv6 only with `--v6-only` argument.
I took the idea from the fork
https://github.com/ad3angel1s/python-zeroconf/blob/master/examples/browser.py
=> examples/browser.py: fix IPv6 addresses output

zeroconf/__init__.py, zeroconf/test.py
Fixes #308
If the packet was too large, it would be rolled back at the end of `write_record`. 
We need to remove the names that were added to the name cache (`self.names`)
as well to avoid a case were we would create a pointer to a name that was
rolled back.
The size of the packet was incorrect at the end after the inserts because
`insert_short` would increase `self.size` even though it was already accounted
before.  To resolve this `insert_short_at_start` was added which does not
increase `self.size`.  This did not cause an actual bug, however it sure
made debugging this problem far more difficult.
Additionally the size now inserted and then replaced when the actual
size is known because it made debugging quite difficult since the size
did not previously agree with the data.
=> Ensure the name cache is rolled back when the packet reaches maximum size

zeroconf/__init__.py
I'm not sure why this code made a new string every time instead of appending to it.
```
(venv) root@ha-dev:~/python-zeroconf# python3 -m timeit -s 'result=""' -u usec 'result = "".join((result, "thisisaname" + "."))'
20000 loops, best of 5: 16.4 usec per loop
(venv) root@ha-dev:~/python-zeroconf# python3 -m timeit -s 'result=""' -u usec 'result += "thisisaname" + "."'
2000000 loops, best of 5: 0.105 usec per loop
```
=> Simplify read_name

zeroconf/__init__.py
Fixes #330 
When using multiple sockets with multi-cast, the outgoing
socket's responses could be read back on the incoming socket,
which leads to duplicate processing and could fill up the
incoming buffer before it could be processed.
This behavior manifested with error similar to
`OSError: [Errno 105] No buffer space available`
By using a single socket with InterfaceChoice.Default
we avoid this case.
=> Use a single socket for InterfaceChoice.Default

zeroconf/__init__.py, zeroconf/test.py
Replaces the solution in #297 with a cleaner implementation.
- Remove the need to trap runtime error
- Only copy the names of the keys when iterating the cache
- Fixes RuntimeError: list changed size during iterating entries_from_name
- Cache services
- The Repear thread is no longer aware of the cache internals
=> Simplify cache iteration

zeroconf/__init__.py, zeroconf/test.py
https://github.com/jstasiak/python-zeroconf/pull/339 with typing fixed
Fixes a regression caused by refactoring error in #331
=> Skip socket creation if add_multicast_member fails (windows)

zeroconf/__init__.py, zeroconf/test.py
- When working with IPv6, multiple AAAA records can exist
for a given host. get_by_details would only return the
latest record in the cache.
- Fix a case where the cache list can change during
iteration
=> Add new cache function get_all_by_details

zeroconf/__init__.py
- The current minimum supported cpython is 3.6+ which does not need
the quoting
=> Remove Callable quoting

zeroconf/__init__.py
- Before
"zeroconf-ServiceBrowser__ssh._tcp.local.-_enphase-envoy._tcp.local.-_hap._udp.local."
"-_nut._tcp.local.-_Volumio._tcp.local.-_kizbox._tcp.local.-_home-assistant._tcp.local."
"-_viziocast._tcp.local.-_dvl-deviceapi._tcp.local.-_ipp._tcp.local.-_touch-able._tcp.local."
"-_hap._tcp.local.-_system-bridge._udp.local.-_dkapi._tcp.local.-_airplay._tcp.local."
"-_elg._tcp.local.-_miio._udp.local.-_wled._tcp.local.-_esphomelib._tcp.local."
"-_ipps._tcp.local.-_fbx-api._tcp.local.-_xbmc-jsonrpc-h._tcp.local.-_powerview._tcp.local."
"-_spotify-connect._tcp.local.-_leap._tcp.local.-_api._udp.local.-_plugwise._tcp.local."
"-_googlecast._tcp.local.-_printer._tcp.local.-_axis-video._tcp.local.-_http._tcp.local."
"-_mediaremotetv._tcp.local.-_homekit._tcp.local.-_bond._tcp.local.-_daap._tcp.loc …
=> Reduce length of ServiceBrowser thread name with many types

zeroconf/__init__.py, zeroconf/test.py
- Previously we would trigger ServiceStateChange.Updated when the
last address we saw changed. Since a host can have multiple addresses
we should only trigger an update when we see a new address.
- Fix race condition in adding records to the cache that could case
consumers of ServiceInfo to miss ip changes.
=> Only trigger a ServiceStateChange.Updated event when an ip address is added

zeroconf/__init__.py, zeroconf/test.py
- If TXT or SRV records update was already processed and then
recieved again, it was possible for a second update to be
called back in the ServiceBrowser
=> Ensure duplicate packets do not trigger duplicate updates

zeroconf/__init__.py
- Closes a small race condition where there were no questions
to ask because the cache was populated in between checks
Avoids `2021-05-27 16:58:15 DEBUG (zeroconf-Engine-240) [zeroconf] Received from '192.168.208.5':5353 (socket 18): <DNSIncoming:{id=13823, flags=288, n_q=0, n_ans=0, n_auth=0, n_add=0, questions=[], answers=[]}> (12 bytes) as [b'5\xff\x01 \x00\x00\x00\x00\x00\x00\x00\x00']`
=> Complete ServiceInfo request as soon as all questions are answered

zeroconf/__init__.py
BREAKING CHANGE
* When manually creating a zeroconf.Engine object, it is no longer started automatically. It must manually be started by calling .start() on the created object.
* The Engine thread is now started after all the listeners have been added to avoid a race condition where packets could be missed at startup.
=> Ensure listeners do not miss initial packets if Engine starts too quickly

zeroconf/test.py
- Ensure the patch target remains in place during the wait
=> Fix flapping test: test_update_record

zeroconf/__init__.py
- There was a short window where the ServiceBrowser thread
could be left running after Zeroconf is closed because
the .join() was never waited for when a new Zeroconf
object was created
=> Ensure ZeroconfServiceTypes.find always cancels the ServiceBrowser

zeroconf/__init__.py
=> Remove unreachable code in ServiceInfo (part 2)

zeroconf/asyncio.py, zeroconf/test_asyncio.py
- Uses the same pattern as ZeroconfServiceTypes.find
closes #405
=> Allow passing in a sync Zeroconf instance to AsyncZeroconf

zeroconf/__init__.py, zeroconf/test.py
- The name must always end with the type or the
constructor will throw BadTypeInNameException
=> Remove unreachable code in ServiceInfo.get_name

zeroconf/__init__.py
- This code is no longer called after a79015e7c4bdc843d97bd5c82ef8ed4eeae01a34
=> Remove is_type_unique as it is unused

zeroconf/__init__.py
- `docstring of zeroconf.ServiceInfo:5: WARNING: Unknown target name: "type".`
Fixes #427
=> Fix warning when generating sphinx docs

zeroconf/__init__.py
These are too large to fix for now so I'm going to disable them inline instead of the `pyproject.toml` as they should be de-monolithed
=> Disable pylint too-many-branches for functions that need refactoring

zeroconf/__init__.py
This will conflict with https://github.com/jstasiak/python-zeroconf/pull/419, but I'll rebase it after
=> Remove unused now argument from ServiceInfo._process_record

zeroconf/__init__.py
`zeroconf/__init__.py:2702:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)`
=> Convert unnecessary use of a comprehension to a list

zeroconf/__init__.py
`zeroconf/__init__.py:830:17: R1714: Consider merging these comparisons with "in" to 'type_ in (_TYPE_CNAME, _TYPE_PTR)' (consider-using-in)`
=> Merge _TYPE_CNAME and _TYPE_PTR comparison in DNSIncoming.read_others

zeroconf/__init__.py
`zeroconf/__init__.py:2336:15: C0113: Consider changing "not err.errno == errno.ENOPROTOOPT" to "err.errno != errno.ENOPROTOOPT" (unneeded-not)`
=> Remove unneeded-not in new_socket

zeroconf/__init__.py
Fixes `zeroconf/__init__.py:2154:0: W0223: Method 'update_service' is abstract in class 'ServiceListener' but is not overridden (abstract-method)`
=> Add missing update_service method to ZeroconfServiceTypes

zeroconf/__init__.py
Alternate to https://github.com/jstasiak/python-zeroconf/pull/446
=> Disable pylint no-self-use check on abstract methods

zeroconf/__init__.py
- This will be fixed in https://github.com/jstasiak/python-zeroconf/pull/419
=> Disable protected-access on the ServiceBrowser usage of _handlers_lock

zeroconf/__init__.py
- Fixes: Instance of 'Exception' has no 'errno' member (no-member)
=> Trap OSError directly in Zeroconf.send instead of checking isinstance

zeroconf/__init__.py
Closes #458
Now that the function is a bit easier to read there are some issues that are apparent:
- `question.name` comparisons are not lower cased in all circumstances (https://github.com/jstasiak/python-zeroconf/issues/463)
- If the type is `_TYPE_ANY` we never respond with PTRs (is this by design or not?) (https://github.com/jstasiak/python-zeroconf/issues/464)
=> Break apart Zeroconf.handle_query to reduce branching

zeroconf/test.py
- Ensures the test relies on the ZeroconfServiceTypes.find making
the correct calls instead of the cache from the previous call
Breakout of https://github.com/jstasiak/python-zeroconf/pull/465
=> Clear cache between ServiceTypesQuery tests

zeroconf/__init__.py
- Adds `add_records` and `remove_records` to `DNSCache` to
permit multiple records to be added or removed in one call
- This change is not enough to remove the too-many-branches
pylint disable, however when combined with #419 it should
no longer be needed
=> Reduce branching in Zeroconf.handle_response

zeroconf/__init__.py
- If the bytes object packed_ip is not the correct length for the
specified address family, ValueError will be raised.
OSError is raised for errors from the call to inet_ntop()
=> Narrow exception catch in DNSAddress.__repr__ to only expected exceptions

zeroconf/asyncio.py
- The call to async_wait should have been in milliseconds, but
the time was being passed in seconds which resulted in waiting
1000x times shorter
=> Fix AsyncServiceInfo.async_request not waiting long enough

zeroconf/__init__.py, zeroconf/test.py, zeroconf/test_asyncio.py
This allows the listener to receive all the records that have
been updated in a single transaction such as a packet or
cache expiry.
`update_record` has been deprecated in favor of `update_records`
A compatibility shim exists to ensure classes that use
`RecordUpdateListener` as a base class continue to have
`update_record` called, however they should be updated
as soon as possible.
A new method `update_records_complete` is now called on each
listener when all listeners have completed processing updates
and the cache has been updated. This allows ServiceBrowsers
to delay calling handlers until they are sure the cache
has been updated as its a common pattern to call for
ServiceInfo when a ServiceBrowser handler fires.
Fixes #416
Fixes #431
Closes #418
Fixes #456
Closes #457
=> RecordUpdateListener now uses update_records instead of update_record

zeroconf/test.py
- The root cause of the test failing should be fixed by #419
and #477
=> Enable test_integration_with_listener_class test on PyPy

Makefile
- If there is a lint problem, we fail before we start running the
tests to ensure the submitter gets feedback right away instead
of waiting for the tests to run.
=> Lint before testing in the CI

zeroconf/__init__.py, zeroconf/test.py
- In order to fix the TC bit not being set, we will need
to be able to check if a DNSOutgoing is a query or
a response
Supports https://github.com/jstasiak/python-zeroconf/pull/494
=> Make a base class for DNSIncoming and DNSOutgoing

zeroconf/__init__.py
- It is not longer necessary to wait since the socketpair
was added in #243 which will cause the select to unblock
when a new socket is added or removed.
=> Remove uneeded wait in the Engine thread

zeroconf/__init__.py, zeroconf/test.py
- The only expected exception is ValueError from calling
the function with a listener that has already been removed
or never added.
Closes #515
=> Remove broad exception catch from RecordManager.remove_listener

README.rst
- When the version requirement changed to cpython 3.6, PyPy
was not bumped as well
closes #508
=> Update python compatibility as PyPy3 7.2 is required

zeroconf/test.py
- Ensure enough time has past that the first record update
was processed before sending the second one
=> Fix flakey test_update_record

tests/test_core.py, tests/test_dns.py, tests/test_init.py, tests/test_services.py, zeroconf/dns.py
- DNSOutgoing.packet only returned a partial message when the
DNSOutgoing contents exceeded _MAX_MSG_ABSOLUTE or _MAX_MSG_TYPICAL
This was a legacy function that was replaced with .packets()
which always returns a complete payload in #248  As packet()
should not be used since it will end up missing data, it has
been removed
closes #542
=> Remove DNSOutgoing.packet backwards compatibility

tests/test_aio.py, tests/test_exceptions.py, zeroconf/__init__.py, zeroconf/_core.py, zeroconf/_dns.py, zeroconf/_exceptions.py, zeroconf/aio.py, zeroconf/services/__init__.py, zeroconf/services/registry.py, zeroconf/utils/name.py
- The public API should only access zeroconf and zeroconf.aio
as internals may be relocated between releases
=> Mark zeroconf.exceptions as protected by renaming to zeroconf._exceptions

setup.cfg
=> Set mypy follow_imports to skip as ignore is not a valid option

tests/services/test_registry.py, zeroconf/_handlers.py, zeroconf/_services/registry.py
- If the ServiceInfo was registered with an uppercase name and the query was
for a lowercase name, it would not be found and vice-versa.
fixes #596
=> Fix lookup of uppercase names in registry

zeroconf/__init__.py
- This class is in the readme, but is not exported by
default
fixes #600
=> Add ZeroconfServiceTypes to zeroconf.__all__

tests/test_dns.py, zeroconf/_dns.py
- Allows storing them in a set for de-duplication
Breakout from https://github.com/jstasiak/python-zeroconf/pull/603
Needed to be able to check for duplicates to solve https://github.com/jstasiak/python-zeroconf/issues/604
=> Make DNSRecords hashable

tests/test_services.py, zeroconf/_services/__init__.py
Needed to fix (partial) https://github.com/jstasiak/python-zeroconf/issues/595
=> Add the ability for ServiceInfo.dns_addresses to filter by address type

tests/test_handlers.py, zeroconf/_handlers.py
- If the PTR or SRV record was suppressed we should not
include the additionals per
https://tools.ietf.org/html/rfc6763#section-12.1
Fixes #613
Broken out from https://github.com/jstasiak/python-zeroconf/pull/603
=> Avoid including additionals when the answer is suppressed by known-answer supression

tests/test_handlers.py, tests/test_services.py, zeroconf/_handlers.py
- Refactor in preparation for fixing https://github.com/jstasiak/python-zeroconf/issues/395 https://github.com/jstasiak/python-zeroconf/issues/595 https://github.com/jstasiak/python-zeroconf/issues/500 https://github.com/jstasiak/python-zeroconf/issues/464 https://github.com/jstasiak/python-zeroconf/issues/604 https://github.com/jstasiak/python-zeroconf/issues/613
- Coverage added in previous PRs to ensure bug-for-bug refactor except for the PTR ending up in both the answers and additionals section (fix partially https://github.com/jstasiak/python-zeroconf/issues/613)
- Adds missing coverage for known answer suppression with service type enumeration queries
=> Breakout the query response handler into its own class

zeroconf/aio.py
- Now that an asyncio event loop is available internally
we can avoid creating another thread.
=> Eliminate aio sender thread

tests/test_init.py, tests/test_services.py
- Switch patching to use unitest.mock.patch to ensure the patch
is reverted when the test is completed
Fixes #505
=> Fix random test failures due to monkey patching not being undone between tests

zeroconf/_services/__init__.py
- The ServiceBrowser would check to see if a DNSAddress was
already in the cache and return early to avoid sending
updates when the address already was held in the cache.
This check was not needed since there is already a check
a few lines before as `self.zc.cache.get(record)` which
effectively does the same thing. This lead to the check
never being covered in the tests and 2 cache lookups when
only one was needed.
=> Remove unreachable cache check for DNSAddresses

tests/services/test_types.py
- We prevent the same record from being multicast within 1s
because of RFC6762 sec 14. Since these test timeout after
0.5s, the answers they are looking for many be suppressed.
Since a legitimate querier will retry again later, we need
to clear the cache to simulate that the record has not
been multicast recently
=> Clear cache in ZeroconfServiceTypes tests to ensure responses can be mcast before the timeout

tests/test_aio.py, zeroconf/_core.py, zeroconf/aio.py
- This safety has existed for a while in the codebase, and should
be extended to async as well.
=> Ensure AsyncZeroconf.async_close can be called multiple times like Zeroconf.close

tests/test_handlers.py
- We prevent the same record from being multicast within 1s
because of RFC6762 sec 14.
=> Ensure cache is cleared before starting known answer enumeration query test

tests/test_services.py, zeroconf/_services/__init__.py
When registering a service, allow_name change can mutate the ServiceInfo.name
=> Ensure the ServiceInfo.key gets updated when the name is changed externally

zeroconf/_services/registry.py
- The key was already available so there was no need to lower
the name
=> Use ServiceInfo.key/ServiceInfo.server_key instead of lowering in ServiceRegistry

tests/test_core.py, tests/test_init.py, zeroconf/_core.py, zeroconf/_services/__init__.py, zeroconf/_services/registry.py
- There was a race condition where a query could be answered for a service
in the registry while goodbye packets which could result a fresh record
being broadcast after the goodbye if a query came in at just the right
time. To avoid this, we now remove the services from the registry right
after we generate the goodbye packet
=> Ensure services are removed from the registry when calling unregister_all_services

tests/utils/test_net.py
=> Ensure interface_index_to_ip6_address skips ipv4 adapters

tests/test_core.py, zeroconf/_core.py
- Switch to using `sys.platform` to detect Mac instead of
`platform.system()` since `platform.system()` is not intended
to be machine parsable and is only for humans.
Closes #650
=> Add test for launching with apple_p2p=True

tests/services/test_types.py
- We need to wait to clear the cache until after the last
service broadcast is processed as it may recreate the cache
=> Fix flakey ZeroconfServiceTypes types test

tests/test_exceptions.py, tests/test_services.py, tests/utils/test_name.py, zeroconf/_utils/name.py
- At least one type "tivo-videostream" exists in the wild
so we are permissive about what we will look for, and
strict about what we will announce.
Fixes #661
=> Permit the ServiceBrowser to browse overlong types

zeroconf/_services/__init__.py
- Since we are passing a type to service_type_name instead of
a name like we do in ServiceInfo the result will always be
true for endswith if it does not generate an exception since
the function always returns the type on the happy path.
=> Remove unreachable BadTypeInNameException check in _ServiceBrowser

tests/services/test_registry.py, zeroconf/_services/registry.py
- In production unregister_service and unregister_all_services
may happen at the same time during shutdown. We want to treat
this as non-fatal since its expected to happen and it is unlikely
that the callers know about each other.
Fixes #675
=> Allow unregistering a service multiple times

tests/test_dns.py, zeroconf/_dns.py
- This class will be used to do fast checks to see
if records should be suppressed by a set of answers.
Supports https://github.com/jstasiak/python-zeroconf/issues/672
=> Add DNSRRSet class for quick hashtable lookups of records

tests/test_dns.py, zeroconf/_dns.py
Supports https://github.com/jstasiak/python-zeroconf/issues/499
=> Add truncated property to DNSMessage to lookup the TC bit

tests/services/test_types.py
- Instead of registering the services and doing the broadcast
we now put them in the registry directly.
=> Remove sleeps from services types test

tests/test_handlers.py
- The flag was added by mistake when copying from other tests
=> Remove AA flags from handlers test

tests/test_handlers.py, zeroconf/_dns.py, zeroconf/_handlers.py
https://datatracker.ietf.org/doc/html/rfc6762#section-5.4
>  When receiving a question with the unicast-response bit set, a
>  responder SHOULD usually respond with a unicast packet directed back
>  to the querier. However, if the responder has not multicast that
>  record recently (within one quarter of its TTL), then the responder
>  SHOULD instead multicast the response so as to keep all the peer
>  caches up to date, and to permit passive conflict detection. In the
>  case of answering a probe question (Section 8.1) with the unicast-
>  response bit set, the responder should always generate the requested
>  unicast response, but it may also send a multicast announcement if
>  the time since the last multicast announcement of that record is more
>  than a quarter of its TTL.
> 
> …
=> Suppress additionals when answer is suppressed

tests/test_core.py
- Fixes flakey test run https://github.com/jstasiak/python-zeroconf/runs/2843523244
=> Fix off by 1 in test_tc_bit_defers_last_response_missing

zeroconf/_dns.py
This one is a bit of a facepalm on my part
=> Rollback data in one call instead of poping one byte at a time in DNSOutgoing

tests/services/test_types.py
Sometimes the packet from the previous test can get multicast back between tests
=> Use unique names in service types tests

tests/test_services.py, zeroconf/_dns.py, zeroconf/_services/__init__.py, zeroconf/aio.py, zeroconf/const.py
- Aggregate queries so that as many known answers as possible fit in the same packet
without having known answers spill over into the next packet unless the
question and known answers are always going to exceed the packet size.
- Some responders do not implement multi-packet known answer suppression
so we try to keep all the known answers in the same packet as the
questions.
- Basic design is extensible to other record types besides PTR, however
we currently don't need to support any other record types.
Fixes #691
=> Efficiently bucket queries with known answers

tests/test_core.py, tests/test_handlers.py, zeroconf/_dns.py, zeroconf/_handlers.py
- Fixes #475
- https://tools.ietf.org/html/rfc6762#section-10.2
Queriers receiving a Multicast DNS response with a TTL of zero SHOULD
NOT immediately delete the record from the cache, but instead record
a TTL of 1 and then delete the record one second later.  In the case
of multiple Multicast DNS responders on the network described in
Section 6.6 above, if one of the responders shuts down and
incorrectly sends goodbye packets for its records, it gives the other
cooperating responders one second to send out their own response to
"rescue" the records before they expire and are deleted.
=> Set stale unique records to expire 1s in the future instead of instant removal

tests/test_protocol.py, zeroconf/_core.py, zeroconf/_dns.py, zeroconf/_handlers.py, zeroconf/_protocol.py, zeroconf/_services/__init__.py
- The created time would differ by a few ms for records, these
should all be the same in each packet to reduce unexpected
inconsistency
- Records received in the same response MUST be subject to fate
sharing.  Its possible we could end up expiring part of the unique
record set because one of the addresses is a few ms older.
Fixes #700
=> Synchronize created time for incoming and outgoing queries

tests/test_handlers.py, zeroconf/_dns.py
Due to the inheritance it was quite confusing to have to set `self.unique` when you wanted a `QU` question
Closes #703
=> Add setter for DNSQuestion to easily make a QU question

tests/test_services.py, zeroconf/_services/__init__.py
- If there were multiple A records for the host, ServiceInfo
would always return the last one that was in the incoming
packet which was usually not the one that was wanted.
=> Fix ServiceInfo with multiple A records

tests/test_handlers.py, tests/test_services.py, zeroconf/_core.py, zeroconf/_handlers.py, zeroconf/_services/__init__.py
- It was too easy to get confused about what was threadsafe and
what was not threadsafe which lead to unexpected failures.
Rename functions to make it clear what will be run in the event
loop and what is expected to be threadsafe
=> Rename handlers and internals to make it clear what is threadsafe

tests/test_cache.py
- There is currently a bug in the implementation where an entry
can exist in two places in the cache with different TTLs. Since
a known answer cannot be both expired and expired at the same
time, this is a bug that needs to be fixed.
=> Add tests for the DNSCache class

tests/test_cache.py, zeroconf/_cache.py
- There should only be one unique record in the cache at
a time as having multiple unique records will different
TTLs in the cache can result in unexpected behavior since
some functions returned all matching records and some
fetched from the right side of the list to return the
newest record. Intead we now store the records in a dict
to ensure that the newest record always replaces the same
unique record and we never have a source of truth problem
determining the TTL of a record from the cache.
=> Fix cache handling of records with different TTLs

tests/test_cache.py, tests/test_services.py, zeroconf/_cache.py
- If the server name had uppercase chars and any of the
matching records were lowercase, the server would not be
found
=> Fix server cache to be case-insensitive

zeroconf/_dns.py, zeroconf/_handlers.py
- RRSet is able to do O(1) lookups of records assuming
there are no collisions.
Builds on the test coverage added in https://github.com/jstasiak/python-zeroconf/pull/734
=> Switch to using DNSRRSet in RecordManager

tests/test_cache.py, tests/test_handlers.py, zeroconf/_cache.py, zeroconf/_core.py, zeroconf/_dns.py, zeroconf/_handlers.py, zeroconf/_services/__init__.py
The majority of our lookups happen in the event loop so there is no need
for them to be threadsafe. Now that the codebase is more clear about what
needs to be threadsafe and what does not need to be threadsafe we can use
the much faster non-threadsafe versions in the places where we are calling
from the event loop.
Supports https://github.com/jstasiak/python-zeroconf/issues/720
=> Add fast cache lookup functions

zeroconf/_services/__init__.py
- The ServiceBrowser had its own cache of the last time it
saw a service which was reimplementing the DNSCache and
presenting a source of truth problem that lead to unexpected
queries when the two disagreed.
Fixes #720
=> Remove second level caching from ServiceBrowsers

tests/test_handlers.py
- The sleep did not account for processing time
=> Fix flakey cache bit flush test

tests/test_core.py, zeroconf/_handlers.py, zeroconf/_services/__init__.py, zeroconf/aio.py
- Calling async_update_records and async_update_records_complete should always
happen in the event loop to ensure implementers do not need to worry about
thread safety
=> Run question answer callbacks from add_listener in the event loop

examples/async_service_info_request.py, tests/services/test_info.py, tests/test_aio.py, zeroconf/_services/info.py, zeroconf/aio.py
- Avoid having to have duplicate code between AsyncZeroconf and Zeroconf
=> Run ServiceInfo requests in the event loop

zeroconf/aio.py
- `self.loop` is no longer used.
=> Remove unused argument from AsyncZeroconf

tests/services/test_browser.py, tests/test_aio.py, tests/test_init.py, zeroconf/_core.py, zeroconf/_handlers.py, zeroconf/_services/browser.py, zeroconf/_utils/aio.py, zeroconf/aio.py
- First step of coordinating multiple ServiceBrowser instances
to solve the excessive queries documented in:
https://github.com/jstasiak/python-zeroconf/issues/721
Supports #721
=> Run ServiceBrowser queries in the event loop

examples/async_browser.py, tests/test_aio.py, zeroconf/aio.py
- These are no longer needed as the base ServiceListener can
now handle both cases
Closes https://github.com/jstasiak/python-zeroconf/issues/753
This is not a breaking change since these never shipped
=> Drop AsyncServiceListener

zeroconf/_services/browser.py
- This guarding is no longer needed as the ServiceBrowser loop
now runs in the event loop and the thread safety guard is no
longer needed
=> Revert: Fix thread safety in _ServiceBrowser.update_records_complete (#708)

tests/services/test_browser.py
- The event was being cleared in the wrong thread which
meant if the test was fast enough it would not be seen
the second time and give a spurious failure
=> Fix race condition in ServiceBrowser test_integration

tests/test_init.py
- This test generated many hosts and tries to send them and
backoff to ensure the incoming buffer does not get full and
incoming starts getting dropped. That did not already work.
Switch to using our _inject_response helper to avoid the
spurious failure since we are not testing the network stack
=> Fix test_lots_of_names overflowing the incoming buffer

zeroconf/_protocol.py
Most packets have a lot of name compression so we can cache reading the
name.
#766
=> Improve performance of parsing DNSIncoming by caching read_utf

zeroconf/_utils/aio.py
We try to shutdown tasks cleanly, but thats not always possible when shutting
down an asyncio event loop from sync since the task list can change and we
need to balance that with waiting too longer for shutdown. 
Its not too important that we wait for tasks since nothing is being stored or written, but
it is nice to have a clean shutdown when possible.
In this case we value fast shutdown over waiting for every task since shutdown
is expected to be idempotent and irreversible anyways.
Seen in the CI here https://github.com/jstasiak/python-zeroconf/pull/774/checks?check_run_id=2870615273
Fixes
```
zeroconf/_core.py:660: in close
self._shutdown_threads()
zeroconf/_core.py:647: in _shutdown_threads
shutdown_loop(self.loop)
zeroconf/_utils/aio.py:80: in shutdown_loop
pending_tasks = …
```
=> Add a guard against the task list changing when shutting down

zeroconf/_services/browser.py
The previous implementation tried to synchronize ServiceBrowser startup and cancel,
however this isn't needed since ServiceBrowsers have always started a separate thread
and have been subject to the startup/shutdown time of the thread.
Fixes deadlock in
```
zeroconf/_services/browser.py:442: in cancel
asyncio.run_coroutine_threadsafe(self._async_cancel_browser(), self.zc.loop).result()
```
https://github.com/jstasiak/python-zeroconf/runs/2870467315
=> Fix deadlock on ServiceBrowser shutdown with PyPy

tests/test_handlers.py, zeroconf/_handlers.py
- When responding to address queries we now always include
other record types (AAAA when asked A, A when asked AAAA)
in the additionals field to provide fate sharing
- This does not implement NSEC records
fixes #771
=> Fix Responding to Address Queries (RFC6762 section 6.2)

zeroconf/_protocol.py
- The cache did not make enough difference to justify the additional
complexity after additional testing was done
=> Drop utf cache from _dns

zeroconf/_services/browser.py, zeroconf/aio.py
- The callback from the listener could generate an event that would
fire in async context that should have gone to the queue which
could result in the consumer running a sync call in the event loop
and blocking it.
Fixes #783
=> Ensure the queue is created before adding listeners to ServiceBrowser

tests/services/test_browser.py, tests/services/test_info.py, zeroconf/__init__.py, zeroconf/_core.py, zeroconf/_dns.py, zeroconf/_services/browser.py, zeroconf/_services/info.py, zeroconf/aio.py
Callers may wish to ask "QU" questions as described in
https://datatracker.ietf.org/doc/html/rfc6762#section-5.4
Supports https://github.com/jstasiak/python-zeroconf/issues/702
=> Add support for requesting QU questions to ServiceBrowser and ServiceInfo

tests/services/test_browser.py, zeroconf/_services/browser.py
- Ensures duplicate question suppression between ServiceBrowsers that
are running in the same zeroconf instances if they become
synchronized (which is likely due to like TTL expire time)
Fixes #789
=> Ensure outgoing ServiceBrowser questions are seen by the question history

tests/test_core.py
Fixes https://github.com/jstasiak/python-zeroconf/pull/793/checks?check_run_id=2874143555
=> Fix test_tc_bit_defers_last_response_missing failures due to thread safety

zeroconf/_dns.py
- On a busy network that receives many mDNS packets per second, we
will not know the answer to most of the questions being asked.
In this case the creating the DNS* objects are usually garbage
collected within 1s as they are not needed. We now set __slots__
to speed up the creation and destruction of these objects
=> Add slots to DNS classes

examples/async_browser.py, examples/browser.py, tests/services/test_browser.py, tests/services/test_info.py, zeroconf/_core.py, zeroconf/_dns.py, zeroconf/_protocol.py, zeroconf/_services/info.py
This replaces https://github.com/jstasiak/python-zeroconf/pull/315 which has been abandoned by the original author.
There are some outstanding problems with the original PR that I'll try to address:
* Is there a better way to provide this functionality than with a new separate API?
* Missing scope_id when IPv6 advertisement received over IPv4. https://github.com/jstasiak/python-zeroconf/pull/315#issuecomment-809827529
* Test coverage decrease.
* Travis CI failed on pypy3.
Closes #314
=> Qualify IPv6 link-local addresses with scope_id

tests/services/test_info.py, zeroconf/_dns.py
We want to check the data that is most likely to be unique first
so we can reject the __eq__ as soon as possible.
https://github.com/jstasiak/python-zeroconf/pull/343#discussion_r656397252
closes https://github.com/jstasiak/python-zeroconf/issues/807
=> Make DNSHinfo and DNSAddress use the same match order as DNSPointer and DNSText

tests/services/test_browser.py, zeroconf/_services/browser.py
https://datatracker.ietf.org/doc/html/rfc6762#section-5.4
When we start a ServiceBrowser and zeroconf has just started up, the known
answer list will be small. By asking a QU question first, it is likely
that we have a large known answer list by the time we ask the QM question
a second later (current default which is likely too low but would be
a breaking change to increase). This reduces the amount of traffic on
the network, and has the secondary advantage that most responders will
answer a QU question without the typical delay answering QM questions.
=> New ServiceBrowsers now request QU in the first outgoing when unspecified

README.rst, tests/services/test_browser.py, zeroconf/_services/browser.py
The ServiceBrowser query loop (async_browser_task) was being awoken on
every packet because it was using `zeroconf.async_wait` which wakes
up on every new packet.  We only need to awaken the loop when the next time
we are going to send a query has changed.
fixes #814 fixes #768
=> Only wake up the query loop when there is a change in the next query time

tests/test_core.py, zeroconf/_core.py
- Oversized packets can quickly overwhelm the system and deny
service to legitimate queriers. In practice this is usually
due to broken mDNS implementations rather than malicious
actors.
Fixes #825
=> Drop oversize packets before processing them

tests/test_aio.py
- This test waits until we get 50 known answers. It would
sometimes fail because it could not ask enough
unsuppressed questions in the allowed time.
Fix additional flapper cases seen during CI runs.
=> Disable duplicate question suppression for test_integration

.github/workflows/ci.yml, Makefile, requirements-dev.txt
Installing deps was taking much longer than running the tests so we now cache them when possible.
=> Cache dependency installs in CI

tests/test_core.py, zeroconf/_core.py
- The suppression was happening per instance of Zeroconf instead
of per interface. Since the same network can be seen on multiple
interfaces (usually and wifi and ethernet), this would confuse the
multi-packet known answer supression since it was not expecting
to get the same data more than once
Fixes #835
=> Make multipacket known answer suppression per interface

.github/workflows/ci.yml
We want to make sure we don't mix pypy and cpython caches.
=> Adjust restore key for CI cache

.github/workflows/ci.yml
There is no need to reinstall dependencies in the CI when we have a cache hit.
=> Skip dependencies install in CI on cache hit

tests/test_core.py, zeroconf/_core.py, zeroconf/_protocol.py
- Only suppress duplicate packets that happen within the same
second. Legitimate queriers will retry the question if they
are suppressed. The limit was reduced to one second to be
in line with rfc6762:
To protect the network against excessive packet flooding due to
software bugs or malicious attack, a Multicast DNS responder MUST NOT
(except in the one special case of answering probe queries) multicast
a record on a given interface until at least one second has elapsed
since the last time that record was multicast on that particular
=> Limit duplicate packet suppression to 1s intervals

tests/services/test_browser.py, tests/services/test_info.py, tests/test_aio.py, tests/test_core.py, tests/test_init.py, tests/utils/test_aio.py
- Use patch in all places so its easier to find where we need
to clean up
`test_integration` was failing often on PyPy since the patching was not effective.  The MacOS github CI runners are very slow so its likely to still fail since we don't wait long enough, but this will make it much more reliable since we won't drop duplicates now in the test.
=> Fix ineffective patching on PyPy

tests/test_aio.py
- The github macOS runners tend to be a bit loaded and these
sometimes fail because of it
=> Increase timeout in test_integration

tests/services/test_types.py
- These tests ran the same test twice in 0.5s and would
trigger the duplicate packet suppression.  Rather then
making them run longer, we can disable the suppression
for the test.
Fixes https://github.com/jstasiak/python-zeroconf/runs/2922685895?check_suite_focus=true
=> Fix spurious failures in ZeroconfServiceTypes tests

tests/services/test_info.py, tests/test_aio.py, zeroconf/_services/info.py
- We want an immediate response when making a request with ServiceInfo
by asking a QU question, most responders will not delay the response
and respond right away to our question. This also improves compatibility
with split networks as we may not have been able to see the response
otherwise.  If the responder has not multicast the record recently
it may still choose to do so in addition to responding via unicast
- Reduces traffic when there are multiple zeroconf instances running
on the network running ServiceBrowsers
- If we don't get an answer on the first try, we ask a QM question
in the event we can't receive a unicast response for some reason
- This change puts ServiceInfo inline with ServiceBrowser which
also asks the first question as QU since ServiceInfo is commonly
called from …
=> Make ServiceInfo first question QU

.github/workflows/ci.yml, requirements-dev.txt
- The github MacOS and Windows runners are slower and
will have the same results as the Linux runners so there
is no need to wait for them.
closes #854
=> Only run linters on Linux in CI

zeroconf/_core.py
- The underlying asyncio code will already handle the exceptions
https://github.com/python/cpython/blob/main/Lib/asyncio/proactor_events.py?rgh-link-date=2021-06-28T02%3A33%3A41Z#L497
https://github.com/python/cpython/blob/main/Lib/asyncio/selector_events.py?rgh-link-date=2021-06-28T02%3A33%3A41Z#L1065
closes #861
=> Ensure protocol and sending errors are logged once

tests/test_core.py, tests/utils/test_aio.py, zeroconf/_core.py, zeroconf/_services/info.py, zeroconf/_utils/aio.py
- Add timeouts in all places where the event loop might get shutdown from under us.
=> Fix deadlock when event loop is shutdown during service registration

tests/test_aio.py
=> Add coverage to ensure unrelated A records do not generate ServiceBrowser callbacks

README.rst
I wasn't sure what to do with `Traffic Reduction` so I do it similar to the `Backwards incompatible changes`
=> Reformat changelog to match prior versions

tests/test_asyncio.py
While playing around with the workaround suggested by @bdraco in #893 I wrote a quick test to see if it would work.
Thought I'd submit the test in case it is a useful addition to the suite.
=> Add test for running sync code within executor

tests/services/test_info.py, tests/test_asyncio.py, tests/utils/test_asyncio.py, zeroconf/_core.py, zeroconf/_services/info.py, zeroconf/_utils/asyncio.py, zeroconf/const.py
It can take a few seconds for a loaded system to run the `async_request` coroutine when the event loop is busy or the system is CPU bound (example being Home Assistant startup).  We now add
an additional `_LOADED_SYSTEM_TIMEOUT` (10s) to the `run_coroutine_threadsafe` calls to ensure the coroutine has the total amount of time to run up to its internal timeout (default of 3000ms). 
Ten seconds is a bit large of a timeout; however, its only unused in cases where we wrap other timeouts. We now expect the only instance the `run_coroutine_threadsafe` result timeout will happen in a production circumstance is when someone is running a `ServiceInfo.request()` in a thread and another thread calls `Zeroconf.close()` at just the right moment that the future is never completed unless the system is …
=> Increase timeout in ServiceInfo.request to handle loaded systems

setup.cfg
- We cannot rename these exceptions now without a breaking change
as they have existed for many years
=> Disable N818 in flake8

zeroconf/_core.py, zeroconf/_services/info.py, zeroconf/_utils/asyncio.py
- Cleanup to ensure all coros we run from a thread
use _LOADED_SYSTEM_TIMEOUT
=> Centralize running coroutines from threads

examples/async_apple_scanner.py, examples/async_browser.py, examples/async_service_info_request.py, examples/browser.py, examples/self_test.py, tests/conftest.py, tests/test_asyncio.py, tests/test_cache.py, tests/test_core.py, tests/test_dns.py, tests/test_exceptions.py, tests/test_handlers.py, tests/test_history.py, tests/test_init.py, tests/test_logger.py, tests/test_protocol.py, tests/test_services.py, tests/test_updates.py, zeroconf/_core.py, zeroconf/_dns.py, zeroconf/_handlers.py, zeroconf/_protocol.py, zeroconf/asyncio.py
- Remove older python syntax as the minimum supported version is 3.6
`pyupgrade --py36-plus tests/*.py zeroconf/*.py examples/*.py`
=> Upgrade syntax to python 3.6

tests/services/test_registry.py, tests/services/test_types.py, tests/test_asyncio.py, tests/test_core.py, tests/test_handlers.py, zeroconf/_core.py, zeroconf/_handlers.py, zeroconf/_services/registry.py
- All calls to the ServiceRegistry are now done in async context
which makes them thread safe. Locking is no longer needed.
=> Remove locking from ServiceRegistry

zeroconf/_core.py
Fixes #917
- The socket was closed during shutdown before asyncio's connection_lost
handler had a chance to close it which resulted in a traceback on
win32.
=> Let connection_lost close the underlying socket

tests/test_handlers.py, zeroconf/_handlers.py
- Solves an exception being thrown when we tried to remove the known answer
from the cache when the second goodbye answer in the same packet was processed
- We previously swallowed all exceptions on cache removal so this was not
visible until 0.32.x which removed the broad exception catch
Fixes #926
=> Handle duplicate goodbye answers in the same packet

tests/test_logger.py, zeroconf/_core.py, zeroconf/_logger.py
- It was difficult to determine which socket was causing
an issue as seen in https://github.com/home-assistant/core/issues/54033
=> Provide sockname when logging a protocol error

tests/services/test_info.py, tests/test_asyncio.py, tests/test_dns.py, tests/test_handlers.py, tests/test_protocol.py, tests/utils/test_net.py, zeroconf/_utils/net.py, zeroconf/const.py
related to #234
The current error on 0.32.1 up to 0.33.2:
```
>>> import zeroconf
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.9/site-packages/zeroconf/__init__.py", line 25, in <module>
from ._cache import DNSCache  # noqa # import needed for backwards compat
File "/usr/lib/python3.9/site-packages/zeroconf/_cache.py", line 26, in <module>
from ._dns import (
File "/usr/lib/python3.9/site-packages/zeroconf/_dns.py", line 28, in <module>
from ._utils.net import _is_v6_address
File "/usr/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 34, in <module>
from ..const import _IPPROTO_IPV6, _MDNS_ADDR6_BYTES, _MDNS_ADDR_BYTES, _MDNS_PORT
ImportError: cannot import name '_MDNS_ADDR6_BYTES' from 'zeroconf.const' …
```
=> Ensure zeroconf can be loaded when the system disables IPv6

tests/conftest.py, tests/services/test_types.py, tests/test_asyncio.py, tests/test_core.py, tests/test_handlers.py, zeroconf/_core.py, zeroconf/_handlers.py, zeroconf/const.py
- Responses are now aggregated when possible per rules in RFC6762 section 6.4
- Responses that trigger the protection against against excessive packet flooding due to
software bugs or malicious attack described in RFC6762 section 6 are delayed instead of discarding as it was causing responders that implement Passive Observation Of Failures (POOF) to evict the records. 
- Probe responses are now always sent immediately as there were cases where they would fail to be answered in time to defend a name.
closes #939
=> Implement Multicast Response Aggregation

tests/test_handlers.py, zeroconf/_handlers.py
- Reduces traffic when we already know we will be sending a group of answers
inside the random delay window described in
https://datatracker.ietf.org/doc/html/rfc6762#section-6.3
closes #944
=> Coalesce aggregated multicast answers when the random delay is shorter than the last scheduled response

tests/test_handlers.py, zeroconf/_core.py, zeroconf/_handlers.py
- Adjust the time windows to ensure responses that have triggered the
protection against against excessive packet flooding due to
software bugs or malicious attack described in RFC6762 section 6
can respond in under 1350ms to ensure ServiceInfo can ask two
questions within the default timeout of 3000ms
=> Ensure ServiceInfo requests can be answered with the default timeout with network protection

zeroconf/_handlers.py
- When building an outgoing response, sort the names together
to increase the likelyhood of name compression. In testing
this reduced the number of packets for large responses
(from 7 packets to 6)
closes #953
=> Sort responses to increase chance of name compression

tests/test_asyncio.py, tests/test_core.py, zeroconf/_core.py
When replying to a QU question, we do not know if the sending host is reachable
from all of the sending sockets. We now avoid this problem by replying via
the receiving socket. This was the existing behavior when `InterfaceChoice.Default`
is set.
This change extends the unicast relay behavior to used with `InterfaceChoice.Default`
to apply when `InterfaceChoice.All` or interfaces are explicitly passed when
instantiating a `Zeroconf` instance.
Fixes #951
Reference https://github.com/home-assistant/core/issues/54531
Reference https://github.com/home-assistant/core/issues/54434
Reference https://github.com/home-assistant/core/issues/54487
=> Send unicast replies on the same socket the query was received

tests/services/test_browser.py, zeroconf/_services/browser.py
- When the PTR response was seen again, the timer was being canceled and
rescheduled even if the timer was for the same time. While this did
not cause any breakage, it is quite inefficient.
=> Only reschedule types if the send next time changes

tests/services/test_info.py, tests/test_handlers.py, zeroconf/_handlers.py
- If we send an answer that is queued to be sent out in the future
we should remove it from the queue as the question has already
been answered and we do not want to generate additional traffic.
=> Add coverage for sending answers removes future queued answers

tests/test_asyncio.py, tests/test_dns.py, zeroconf/_dns.py
- The hash was being recalculated every time the object
was being used in a set or dict. Since the hashes are
effectively immutable, we only calculate them once now.
Closes #959
=> Cache DNS record and question hashes

README.rst, zeroconf/_core.py
Fixes IPv6 service discovery on Windows and  supports service discovery on specified interface indexes, and IP addresses - both on Windows and Linux.
Closes #932
=> Create full IPv6 address tuple to enable service discovery on Windows

tests/test_dns.py, zeroconf/_dns.py
- These records should have the same hash and equality since
the unique bit is not considered when adding or removing
the records from the cache
=> Fix equality and hash for dns records with the unique bit

tests/services/test_registry.py, tests/test_asyncio.py, tests/test_handlers.py, zeroconf/_core.py
- If a ServiceInfo that used the same server name as another ServiceInfo
was unregistered, goodbye packets would be sent for the addresses and
would cause the other service to be seen as offline.
=> Skip goodbye packets for addresses when there is another service registered with the same name

tests/test_handlers.py, zeroconf/_handlers.py
Implements https://datatracker.ietf.org/doc/html/rfc6762#section-6.2
=> Include NSEC records for non-existant types when responding with addresses

zeroconf/_protocol.py
Reduces the algorithmic complexity of `write_name`
Before
After
=> Reduce name compression overhead and complexity

zeroconf/_core.py
- This hook was primarily used for threads that no longer exist.
- Since there the other attributes are not protected, it was inconsistent to
protect this one.
=> Collapse _GLOBAL_DONE into done

zeroconf/_handlers.py, zeroconf/_protocol.py
- Right now we decode all known the answers in the packet even if we never need to look at them because we can't answer any of the questions in the packet
- Decoding packets is the most expensive operation zeroconf performs on active networks. In fact it's the most expensive operation on a mostly idle home assistant instance.
- Defer decoding to only when we need to check for suppression to save cpu time.
- Closes #980
=> Defer decoding known answers until needed

zeroconf/__init__.py, zeroconf/_core.py, zeroconf/_utils/net.py
- There is no need to call can_send_to when we derive the target
since we already know we can send to it.
- can_send_to was converting the addr string into an ipaddress object
to check if it was IPv4 or IPv6. Since this all happens internally there
was no need for the additional validation and check. We can use a must
more simple test.
=> Simplify the can_send_to check

tests/test_core.py, zeroconf/_core.py, zeroconf/_handlers.py
- logging would make calls to look up socket information and then discard it if the log level was not debug.
=> Reduce logging overhead

tests/test_protocol.py, zeroconf/_core.py, zeroconf/_protocol/incoming.py
- The choked wording makes it seems like there is a problem in zeroconf when
the usual case was an invalid packet send or corrupt wire data.
closes #993
=> Improve log message when receiving an invalid or corrupt packet

zeroconf/_protocol/incoming.py
- decode is a bit faster vs str()
```
>>> ts = Timer("s.decode('utf-8', 'replace')", "s = b'TV Beneden (2)\x10_androidtvremote\x04_tcp\x05local'")
>>> ts.timeit()
0.09910525000003645
>>> ts = Timer("str(s, 'utf-8', 'replace')", "s = b'TV Beneden (2)\x10_androidtvremote\x04_tcp\x05local'")
>>> ts.timeit()
0.1304596250000145
```
=> Optimize decoding labels from incoming packets

tests/utils/test_net.py, zeroconf/_utils/net.py
This prevents a crash on Python versions < 3.9 when scope_id is supplied in the address, and also fixes finding the related interface.
In preparation of home assistant moving to minimal-Python 3.9 requirement, and enabling scope_ids via https://github.com/home-assistant/core/blob/a90c8ab5584ce50e8dfae67790cb56f3d1d1ea86/homeassistant/components/network/__init__.py#L55.
=> Strip scope_id from IPv6 address if given.

tests/services/test_browser.py, tests/test_asyncio.py, zeroconf/_utils/time.py
Prevent service lookups from deadlocking if time abruptly moves backwards
- Usually via an ntp update
=> Prevent service lookups from deadlocking if time abruptly moves backwards

tests/utils/test_net.py, zeroconf/_utils/net.py
- We already skip these when adding multicast members.
Apply the same logic to the socket bind call
Reference https://github.com/home-assistant/core/issues/57678
=> Skip unavailable interfaces during socket bind

tests/utils/test_asyncio.py, zeroconf/__init__.py, zeroconf/_core.py, zeroconf/_exceptions.py, zeroconf/_services/info.py, zeroconf/_utils/asyncio.py
While run_coro_with_timeout is never expected to timeout during
normal operation, we want to provide additional clarity to
help the developer track down the cause when run_coro_with_timeout
unexpectedly reaches a timeout.
related https://github.com/home-assistant-libs/pychromecast/issues/560
=> Throw EventLoopBlocked instead of concurrent.futures.TimeoutError

tests/test_exceptions.py
Adds two tests with instance names containing dots, which
are currently not handled correctly.
Reproducer for https://github.com/jstasiak/python-zeroconf/issues/146
Maintainers: You probably don't want to merge this PR as long as the underlying issue is not fixed.
=> Add tests for instance names containing dot(s)

tests/services/test_browser.py, tests/test_services.py, zeroconf/_handlers.py, zeroconf/_services/browser.py
Fixes erroneous match with service names that have a type that ends with a shorter type.
Given "%NAS._asustor-looksgood_http._tcp.local.",
type "_asustor-looksgood_http._tcp.local." should not match "_http._tcp.local."
My example: currently with an Asustor NAS the "%NAS._asustor-looksgood_http._tcp.local." service appears to have a "_http._tcp.local." service_type while its actual type is "_asustor-looksgood_http._tcp.local."  
This causes an exception because the ServiceInfo __init__ checks:
```
if not type_.endswith(service_type_name(name, strict=False)):
raise BadTypeInNameException
File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 405, in _process_service_update
async_service_info = AsyncServiceInfo(service_type, name)
File …
```
=> Handle Service types that end with another service type

README.rst
I ran bump2version too early before I updated the changelog so we get two version number bumps
=> Update changelog for 0.38.2/3

tests/services/test_browser.py, zeroconf/_core.py
ServiceBrowsers were only getting a `ServiceStateChange.Removed` callback when the record was sent with a TTL of 0.  They now correctly get a `ServiceStateChange.Removed` callback when the record expires as well.
cc @AlexxIT
=> Fix ServiceBrowsers not getting `ServiceStateChange.Removed` callbacks on PTR record expire

tests/services/test_browser.py
The `QuestionHistory` guards were causing random test failures
=> Use unique name in test_service_browser_expire_callbacks test

zeroconf/_protocol/incoming.py
use 	`struct.Struct` to avoid building the unpacks each call as it saves a non-trivial amount of work especially with small values.
This makes the most difference if the rest of the program is doing > 100 different unpacks since it will avoid the case were the cache is exhausted
https://github.com/python/cpython/blob/f9585e2adc36fb2886f96ef86a5aa14215fc1151/Modules/_struct.c#L2103
=> Speed up unpacking incoming packet data

requirements-dev.txt, setup.py, zeroconf/_utils/asyncio.py
Its unlikely that https://bugs.python.org/issue39032 and
https://github.com/python/cpython/issues/83213 will be fixed
soon. While we moved away from an `asyncio.Condition`, we still
has a similar problem with waiting for an `asyncio.Event` which
`wait_event_or_timeout` played well with. `async_timeout` avoids
creating a task so its a bit more efficient. Since we call
these when resolving `ServiceInfo`, avoiding task creation
will resolve a performance problem when `ServiceBrowser`s
startup as they tend to create task storms when coupled
with `ServiceInfo` lookups.
=> Replace wait_event_or_timeout internals with async_timeout

bench/incoming.py, zeroconf/_protocol/incoming.py
We did not cache the result of the final decode which meant any label that
used the final decode as part of a future decode had to be decoded again
=> Improve cache of decode labels at offset

tests/services/test_info.py, zeroconf/_services/info.py
If there were multiple dns service records it was possible that a port change could be missed.
=> Fix port changes not being seen by ServiceInfo

tests/services/test_info.py, zeroconf/_services/info.py
We previously assumed we should only update the address when the server changed, but we need to handle ip changes.
Related issue https://github.com/home-assistant/core/issues/80211
=> Fix IP changes being missed by ServiceInfo

poetry.lock, pyproject.toml, src/zeroconf/_utils/asyncio.py
We now use the built-in asyncio.timeout instead
when running on python 3.11+
=> feat: drop async_timeout requirement for python 3.11+

pyproject.toml
The project name was set incorrectly when the release automation was added
=> fix: fix project name in pyproject.toml

src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py
=> feat: optimize incoming parser by reducing call stack

bench/outgoing.py, src/zeroconf/_protocol/outgoing.pxd, src/zeroconf/_protocol/outgoing.py, tests/test_core.py
This is ~27% speed up.  We can get some more by optimizing the packing but the bulk of the run time is incoming so its likely not worth the maintenance burden to keep the pxd file in sync unless someone has a use case were they construct many outgoing packets.
=> feat: optimize construction of outgoing packets

src/zeroconf/_dns.pxd, src/zeroconf/_dns.py
By moving some of the equality checking to `cdef`s we can avoid the generic python accessors and access the properties directly on the object. This can only be done once it passes the `isinstance` check for the same type.
=> feat: optimize equality checks for DNS records

src/zeroconf/_dns.pxd, src/zeroconf/_dns.py, tests/services/test_browser.py, tests/test_dns.py
The `name` check is already using the `key` (lowercase value) but the `server` and `alias` did not use their respective keys
There are likely more cases where we don't handle this perfectly https://datatracker.ietf.org/doc/html/rfc4343#section-2
fixes #1121
=> fix: the equality checks for DNSPointer and DNSService should be case insensitive

.pre-commit-config.yaml, poetry.lock
need to update poetry as well to get the ci to pass on windows
=> chore: bump isort to 5.12.0 to fix ci

src/zeroconf/_services/browser.py
see https://github.com/python/cpython/issues/88831
fixes #1126
=> fix: hold a strong reference to the query sender start task

src/zeroconf/_core.py
There are still cases were we cannot answer questions fast enough to keep up with systems (mainly HomeKit) that require a response within a time period to prevent a device from going offline.
This change saves a bit of time by pre-calculating most of the work needed to work out how to send.
We need to optimize the handlers a bit as well via https://github.com/python-zeroconf/python-zeroconf/pull/1136
=> feat: reduce overhead to send responses

src/zeroconf/_handlers.py
We can use a normal set instead of a DNSRRSet for
for _async_mark_unique_cached_records_older_than_1s_to_expire
=> feat: speed up processing incoming records

src/zeroconf/_services/__init__.py
We were making a copy of the handler list every time a change was fired. We can use a view instead to avoid the list changed during iteration problem until we can refactor to only change the handler list in the event loop.
=> feat: small speed up to handler dispatch

src/zeroconf/_services/info.py
Since we see the same IP addresses over and over it pays off to cache the construction of them.
The cache hit rate is nearly 100% after the first time its seen.
```
2023-04-01 02:55:32.822 CRITICAL (SyncWorker_4) [homeassistant.components.profiler] Cache stats for lru_cache <function ip_address at 0x7f4e727dc790> at /usr/local/lib/python3.10/ipaddress.py: CacheInfo(hits=2239, misses=147, maxsize=1024, currsize=147)
2023-04-01 02:55:54.610 CRITICAL (SyncWorker_4) [homeassistant.components.profiler] Cache stats for lru_cache <function ip_address at 0x7f4e727dc790> at /usr/local/lib/python3.10/ipaddress.py: CacheInfo(hits=2434, misses=160, maxsize=1024, currsize=160)
2023-04-01 02:57:39.852 CRITICAL (SyncWorker_3) [homeassistant.components.profiler] Cache stats for lru_cache <function …
```
=> feat: improve performance of constructing ServiceInfo

pyproject.toml
Include documentation and test files in source distributions, in order to make them more useful for packagers (Linux distributions, Conda). Testing is an important part of packaging process, and at least Gentoo users have requested offline documentation for Python packages. Furthermore, the COPYING file was missing from sdist, even though it was referenced in README.
=> feat: include tests and docs in sdist archives

src/zeroconf/_services/browser.py, src/zeroconf/_utils/name.py
Avoids some isinstance checks and uses an lru to generate the possible types.  The LRU has a good hit rate:
```
2023-04-02 05:46:07.886 CRITICAL (SyncWorker_8) [homeassistant.components.profiler] Cache stats for lru_cache <function possible_types at 0x7f0e818d4dc0> at /usr/local/lib/python3.10/site-packages/zeroconf/_utils/name.py: CacheInfo(hits=1989, misses=375, maxsize=256, currsize=256)
2023-04-02 05:47:07.352 CRITICAL (SyncWorker_13) [homeassistant.components.profiler] Cache stats for lru_cache <function possible_types at 0x7f0e818d4dc0> at /usr/local/lib/python3.10/site-packages/zeroconf/_utils/name.py: CacheInfo(hits=2283, misses=387, maxsize=256, currsize=256)
2023-04-02 05:48:04.247 CRITICAL (SyncWorker_15) [homeassistant.components.profiler] Cache stats for lru_cache <function …
```
=> feat: speed up matching types in the ServiceBrowser

src/zeroconf/_services/browser.py, src/zeroconf/asyncio.py
Splits the code into the class for sync and async to avoid the branching in the base class
=> feat: speed up processing records in the ServiceBrowser

src/zeroconf/_services/info.py, tests/services/test_info.py
Consumers of zeroconf commonly have to recreate the ip_address objects which has a bit of overhead. Since we are using the built-in objects there is little risk of the API changing in the future. They are now available as ip_addresses_by_version
=> feat: add ip_addresses_by_version to ServiceInfo

src/zeroconf/_services/browser.py, src/zeroconf/asyncio.py
OrderedDict is no longer needed since 3.7 is the minimum python version we support and insertion order is a strong guarantee for `dict` now. Additionally we can avoid the popitem pattern since async_update_records_complete runs in the event loop and does not need to worry about thread-safety
=> feat: improve ServiceBrowser performance by removing OrderedDict

src/zeroconf/_services/info.py, tests/services/test_info.py
`parsed_scoped_addresses` would not return addresses in the same order as the other address functions. This lead to unexpected results with the `host` value. 
Addresses are guaranteed to be returned in LIFO (last in, first out)
order with IPv4 addresses first and IPv6 addresses second.
This means the first address will always be the most recently added
address of the given IP version.
This also improves performance of ip address handling in ServiceInfo as there were multiple conversions that can be avoided when processing IP Addresses
=> fix: make parsed_scoped_addresses return addresses in the same order as all other methods 

src/zeroconf/_core.py, src/zeroconf/_handlers.py, src/zeroconf/_services/info.py, src/zeroconf/_services/registry.py, tests/services/test_info.py, tests/test_asyncio.py, tests/test_handlers.py
If the server name changed we would return the addresses for the old server name.
If the server name differed from the record name we would include the wrong addresses if the SRV record was not already in the cache because we would never ask for it and use the record name to lookup the A/AAAA records.
The downside is that this will likely increase the number of network requests but https://github.com/python-zeroconf/python-zeroconf/pull/1153 should mitigate the impact of that a bit
=> fix: addresses incorrect after server name change

src/zeroconf/_handlers.py
If there is a device with a bad mdns stack that is flooding the network with response packets there is little we can do but optimize how we handle this as mdns works on a trust model of generally accepting network traffic. Its unlikely that the user is going to remove the offending the device so we will reduce the overhead to deal with one of these.
=> feat: reduce denial of service protection overhead

src/zeroconf/_dns.pxd, src/zeroconf/_dns.py, src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py
This is roughly a 4.5% speed up against the incoming benchmark
=> feat: speed up incoming data parser

src/zeroconf/_services/browser.py
There were so many casts being called here they showed up on the profiler since they were inside the set comp
=> fix: reduce cast calls in service browser

src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py
`DNSQuestion` is now imported via cimport to reduce overhead. The unpack dispatch is avoided to reduce the stack overhead
=> feat: speed up decoding dns questions when processing incoming data

src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py
This is ~4% speed up on the incoming data processing benchmark
=> feat: speed up processing incoming data

src/zeroconf/_services/browser.py, tests/test_asyncio.py
The bulk of the time was spent checking to see if queries were ready to go out from the reschedule which checks every type the ServiceBrowser has configured. Since we are only adjusting one type we can guard this with a simple check to avoid checking every type
=> feat: improve performance of ServiceBrowser outgoing query scheduler

src/zeroconf/_core.py, src/zeroconf/_handlers.py, src/zeroconf/_services/registry.py, tests/services/test_registry.py, tests/test_handlers.py
Every lookup was doing .lower() on the input after #597. Since we only feed this data in via handlers and core, we should lower the name before feeding it into the registry to avoid doing it 1000s of times
=> feat: speed up the service registry

src/zeroconf/_services/info.py
Most of the reply overhead was because of the enums which happens A LOT if there are homekit devices on the network
=> feat: reduce overhead to enumerate ip addresses in ServiceInfo

build_ext.py, src/zeroconf/_protocol/outgoing.pxd, src/zeroconf/_protocol/outgoing.py
Adds some more cython types to avoid `getattr` overhead
=> feat: optimize construction of outgoing dns records

src/zeroconf/_handlers.py
- adds slots to handler classes
- avoid any expression overhead and inline instead
=> feat: reduce overhead to handle queries and responses

src/zeroconf/_core.py, tests/test_core.py
I only noticed these were missing when I ran the profiler on a system with IPv6
=> fix: reduce debug logging overhead by adding missing checks to datagram_received

src/zeroconf/_services/info.py, tests/services/test_info.py
Passing `addr` and `port` is optional, and will default to the mDNS multicast address and port. This is useful for directing requests to a specific host that may be able to respond across subnets.
=> feat: add support for sending to a specific `addr` and `port` with `ServiceInfo.async_request` and `ServiceInfo.request`

src/zeroconf/_core.py, src/zeroconf/_logger.py, src/zeroconf/_services/__init__.py, src/zeroconf/_services/browser.py, src/zeroconf/_services/registry.py
- Make a few more classes that do not need dynamic attributes slotted
=> feat: improve incoming data processing performance

src/zeroconf/_services/browser.py
This is a small cleanup but the primary goal here it to do a rebuild with cython 3
=> fix: add missing if TYPE_CHECKING guard to generate_service_query

src/zeroconf/_services/__init__.py, src/zeroconf/_services/info.py
There were still some places where we are using `address` which should be `ip_addr`
Remove some of the expensive isinstance checks as well.
=> fix: cleanup naming from previous refactoring in ServiceInfo

src/zeroconf/_services/info.py
When there are many lookups at once, this can overload the system. Refactor to use faster primitives
This block disappears from the profile after this change
=> fix: improve performance of ServiceInfo.async_request

src/zeroconf/_services/info.py
If async_request timed out at just the wrong time it could result in an InvalidStateError
```
2023-08-02 19:29:06.131 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Future.set_result(None)
File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
```
This was harmless but created noise
=> fix: race with InvalidStateError when async_request times out

src/zeroconf/_dns.pxd
fixes #1207
This seems to cause a problem for some systems. Its not clear why but this is likely the only change that could have triggered the issue so lets revert it
=> fix: revert DNSIncoming cimport in _dns.pxd

src/zeroconf/_dns.py
fixes #1207
This causes a cython compile crash
=> fix: revert adding typing to DNSRecord.suppressed_by

src/zeroconf/_utils/name.py
This function gets called all over the place and when we construct a lot of ServiceInfos for queries its the most expensive part. Since we tend to query the same records over and over when a ServiceBrowser is running, this can have quite a cost
=> feat: add a cache to service_type_name

src/zeroconf/_services/info.py
We now defer unpacking this until the property is accessed 
The exception catch was a bit of a problem when processing a lot of records when looking at the profiling from https://github.com/postlund/pyatv/pull/2122
=> feat: speed up unpacking text records in ServiceInfo

src/zeroconf/_dns.py
fixes #1207
```
Cythonizing src/zeroconf/_dns.py
Error compiling Cython file:
------------------------------------------------------------
...
def is_recent(self, now: _float) -> bool:
"""Returns true if the record more than one quarter of its TTL remaining."""
return self.created + (_RECENT_TIME_MS * self.ttl) > now
def reset_ttl(self, other: 'DNSRecord') -> None:
^
------------------------------------------------------------
src/zeroconf/_dns.py:210:24: Compiler crash in AnalyseDeclarationsTransform
File 'ModuleNode.py', line 124, in analyse_declarations: ModuleNode(_dns.py:1:0,
doc = ' Multicast DNS Service Discovery for Python, v0.14-wmcbrine\n    Copyright 2003 Paul Scott-Murphy, 2014 William McBrine\n\n    This module provides a framework for the use of DNS Service Discovery\n …
```
=> fix: remove typing on reset_ttl for cython compat

src/zeroconf/_core.py, src/zeroconf/_services/info.py, src/zeroconf/_utils/asyncio.py
Noticed this while profiling the esphome code as it adds/remove listeners every time its trying to connect to an offline device
=> feat: refactor notify implementation to reduce overhead of adding and removing listeners

src/zeroconf/_handlers.py, src/zeroconf/_services/registry.py, tests/test_handlers.py
There were still a few places where we called `.keys()` when its the default.
=> chore: remove default calls to .keys()

src/zeroconf/_services/browser.py, src/zeroconf/_services/info.py, src/zeroconf/_updates.py, tests/services/test_info.py
These classes used to process a single record at a time, but since we now process them all in batches, we can remove all the breakout functions.  This will also fix futures not resolving since the legacy backcompat was partially broken in info.py
This removes the legacy `update_record` as its been a few years now from `info.py`, but leaves the one in `_updates.py` for back-compat as it appears some libs are not updated yet
https://github.com/python-zeroconf/python-zeroconf/blob/b492eb4204e433dec7b9f9a1c79525649ef33b5c/src/zeroconf/_updates.py#L43
https://github.com/python-zeroconf/python-zeroconf/blob/b492eb4204e433dec7b9f9a1c79525649ef33b5c/src/zeroconf/_services/info.py#L413
=> feat: optimize processing of records in RecordUpdateListener subclasses

src/zeroconf/_services/registry.py
=> fix: build failures with older cython 0.29 series

build_ext.py, src/zeroconf/_history.pxd, src/zeroconf/_history.py, tests/__init__.py, tests/services/test_browser.py, tests/test_asyncio.py, tests/test_handlers.py, tests/test_listener.py
The frequent call to async_expire is the main source of cpu time here
=> feat: speed up question and answer history with a cython pxd

src/zeroconf/_services/browser.py, src/zeroconf/asyncio.py, tests/services/test_browser.py, tests/test_asyncio.py
I started using this package for the first time recently, and when trying to use the [async browser example](https://github.com/python-zeroconf/python-zeroconf/blob/master/examples/async_browser.py), I found the requirement to use `AsyncServiceBrowser.async_cancel()` at the end of everything. After discovering that AsyncZeroconf has an async context manager, I found that AsyncServiceBrowser did not have its own.
I tried my best to replicate #284 (#177), however I am not sure how to go about adding test coverage. Apologies for not adding any.
Here's an example of how my code is simplified using the context manager (in Python 3.11):
```
async def main():
services = ["_example._tcp.local."]
async with (
AsyncZeroconf() as aiozeroconf,
AsyncServiceBrowser(aiozeroconf.zeroconf, services, …
```
=> feat: context managers in ServiceBrowser and AsyncServiceBrowser

src/zeroconf/_core.py, src/zeroconf/_services/info.py
This is a small cleanup to avoid calling .lower() when we already have the server_key. performance benefit is negligible
=> feat: use server_key when processing DNSService records

build_ext.py, src/zeroconf/_listener.pxd, src/zeroconf/_utils/time.pxd, src/zeroconf/_utils/time.py
When the mac discovery app is open, the number of questions goes up almost 10x. We can reduce a bit of the overhead by cythonizing the time functions and cimporting it into the hot path
=> feat: reduce overhead to process incoming questions

src/zeroconf/_listener.pxd, src/zeroconf/_listener.py
There were quite a few float to pyfloat conversion that can be avoided by adding cdefs
=> feat: avoid python float conversion in listener hot path

src/zeroconf/_core.py, src/zeroconf/_listener.pxd, src/zeroconf/_listener.py, src/zeroconf/_protocol/incoming.pxd, tests/__init__.py, tests/services/test_info.py, tests/test_asyncio.py, tests/test_core.py, tests/test_handlers.py
handle_response was left over from before async_updates_from_response was moved into the record manager. Call the record manager directly from the listener instead so we can use a cimport to avoid converting back to python objects
=> feat: reduce overhead to process incoming updates by avoiding the handle_response shim

src/zeroconf/_services/info.py
`_set_ipv4_addresses_from_cache` and `_set_ipv6_addresses_from_cache` were useless calls because they would always load the same data that was being fed into the function from `load_from_cache` or nothing if there was nothing in the cache. Removing them has the same result because the data was being loaded twice when there was data in the cache.
=> fix: remove useless calls in ServiceInfo

src/zeroconf/_core.py, src/zeroconf/_handlers/query_handler.py, src/zeroconf/_services/info.py, tests/services/test_browser.py, tests/test_handlers.py
- Anything we save for a query response does not need a created time since we only use this for records we are not authoritative for.  These records are good until they unregistered.
- The query_handler was constructing records for every question, when they never change once registered in the registry
Someone could be mutating the data after they register the `ServiceInfo` but that would be wrong anyways since they should be calling `async_update_service` with new `ServiceInfo` since any changes wouldn't be broadcast anyways.
This is not as clean as I would have liked it to be as we have to maintain backwards compat for `override_ttl`
=> feat: cache construction of records used to answer queries from the service registry

src/zeroconf/_core.py, src/zeroconf/_handlers/record_manager.pxd, src/zeroconf/_handlers/record_manager.py, src/zeroconf/_services/info.py
Listeners were stored in a list which meant a linear search had to happen to remove them. We add/remove these quite a bit when resolving a service, also ESPHome churns these quite a bit when a device is offline.
Technically breaking change: `Zeroconf.listeners` now returns a `set` instead of a `list`
Technically breaking change: `ServiceInfo.__eq__` is now the default python implementation as it wasn't hashable otherwise and comparing on `name` was wrong since it wasn't case aware
=> feat: speed up adding and removing RecordUpdateListeners

src/zeroconf/_services/info.py
We already have the loop available as `zc.loop`
At Home Assistant startup we have a thundering heard of ServiceInfos being resolved. Avoid the get_running_loop() calls since it generates `os.getpid()` syscalls
=> feat: avoid calling get_running_loop when resolving ServiceInfo

build_ext.py, src/zeroconf/_handlers/answers.pxd, src/zeroconf/_handlers/answers.py
Adds a cython pxd for zeroconf._handlers.answers
=> feat: speed up generating answers

build_ext.py, src/zeroconf/__init__.py, src/zeroconf/_engine.py, src/zeroconf/_handlers/record_manager.py, src/zeroconf/_record_update.py, src/zeroconf/_services/browser.py, src/zeroconf/_services/info.py, src/zeroconf/_updates.pxd, src/zeroconf/_updates.py
This should effectively do nothing except make ServiceInfo cythonable since cython requires the base class to be a cdef
=> chore: prepare ServiceInfo base class RecordUpdateListener for cython

build_ext.py, src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py
Its a shame that `dns_text`, `dns_pointer` etc take kwargs as we could make them cdefs as they are really what gets called the most here when using Homekit.  We could change the function signatures but I've already found code in the while calling it so it would be a breaking change for them.
=> feat: speed up ServiceInfo with a cython pxd

src/zeroconf/_dns.pxd, src/zeroconf/_dns.py, src/zeroconf/_handlers/answers.pxd, src/zeroconf/_handlers/answers.py, src/zeroconf/_handlers/query_handler.pxd
Use cythoned classes instead of named tuples since named tuples can't be fully cythonized.
These didn't need to be named tuples because they are never unpacked and always accessed by name anyways
Add some more types in the answer path
=> feat: speed up question and answer internals

src/zeroconf/_services/browser.pxd, src/zeroconf/_services/browser.py, src/zeroconf/asyncio.py
provide default handler for `async_update_records_complete` in `_ServiceBrowserBase`
`async_update_records_complete` is no longer an abstract method in `_ServiceBrowserBase` and a default handler is now provided which was originally in `AsyncServiceBrowser`.  This allows us to cythonize the function and use the fast PyDict methods since its called so frequently when a browser is running.
It is still expected that `async_update_records_complete` can be overridden in subclasses, but it is recommended to subclass `ServiceBrowser` or `AsyncServiceBrowser` directly instead of `_ServiceBrowserBase` since the `_` indicates `_ServiceBrowserBase` is protected and its internal api is not public (or stable)
=> feat: improve AsyncServiceBrowser performance

src/zeroconf/_dns.pxd, src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py
=> feat: improve performance of loading records from cache in ServiceInfo

build_ext.py, src/zeroconf/_handlers/answers.pxd, src/zeroconf/_handlers/multicast_outgoing_queue.pxd, src/zeroconf/_handlers/multicast_outgoing_queue.py
- adds a cython pxd
This is the last of the handlers to need a pxd
=> feat: speed up outgoing multicast queue

src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py, src/zeroconf/_services/registry.py, tests/conftest.py, tests/test_asyncio.py
If the service info was modified in place the update would not be reflected when calling async_update_service.
This wasn't an expected use case, but it happens in the wild.
=> fix: ensure ServiceInfo cache is cleared when adding to the registry

src/zeroconf/_handlers/multicast_outgoing_queue.pxd, src/zeroconf/_handlers/query_handler.pxd, src/zeroconf/_handlers/record_manager.pxd, src/zeroconf/_listener.pxd, src/zeroconf/_protocol/outgoing.pxd, src/zeroconf/_services/browser.pxd, src/zeroconf/_services/info.pxd
There was no need for TYPE_CHECKING to be an object which requires a jump back into python code
=> feat: reduce type checking overhead at run time

src/zeroconf/_services/browser.pxd, tests/conftest.py, tests/services/test_browser.py, tests/test_handlers.py
Some of the tests started failing because of fixes to the CI process where we were not properly testing with cython since the patch targets were not patchable.
=> chore: fix test patching

src/zeroconf/_listener.pxd, src/zeroconf/_listener.py, tests/test_listener.py
Splits `datagram_received` into `_process_datagram_at_time` so it can be tested directly
=> chore: fix duplicate packet test with cython

tests/test_dns.py
time can move forward too slowly or quickly for these tests on the github runners
=> chore: fix race in dns tests

src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py
All the single char conversions can avoid the bytes copy, and since there are a lot of them this is ~ an 8% speed up
=> feat: speed up incoming packet processing with a memory view

build_ext.py, src/zeroconf/_cache.pxd, src/zeroconf/_handlers/query_handler.py, src/zeroconf/_record_update.pxd, src/zeroconf/_record_update.py, src/zeroconf/_services/browser.pxd, src/zeroconf/_services/browser.py, src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py, src/zeroconf/_updates.py, tests/test_updates.py
- adds more cython types
- convert `RecordUpdate` to a base class since NamedTuple has the unfortunate side effect of running a lambda on creation which can't be optimized away
=> feat: speed up record updates

.github/workflows/ci.yml
The wheels were taking more than 5 hours to build
=> fix: skip wheel builds for eol python and older python with aarch64

.github/workflows/ci.yml
qemu is far too slow so we will only build wheels for cpython 3.11/3.12 with aarch64
=> fix: do not build aarch64 wheels for PyPy

.github/workflows/ci.yml
The last build almost hit the 6 hour limit due to qemu being too slow. We only really need the aarch64 for debian at this point so remove the ones that were just added as there are likely no other consumers of the alpine wheels other than HA which builds their own anyways
=> fix: do not build musllinux aarch64 wheels to reduce release time

src/zeroconf/_listener.pxd, src/zeroconf/_listener.py, src/zeroconf/_services/registry.pxd, src/zeroconf/_services/registry.py, tests/test_core.py, tests/test_listener.py
If there is nothing in the ServiceRegistry we would still process incoming questions. If we have no answers to give, we can skip the handling queries completely as it significantly reduces cpu time.
This is expected to significantly reduce cpu time for one shot usage
=> feat: speed up instances only used to lookup answers

pyproject.toml
cython 0.29.x is no longer recommended by cython and since 3.x fixes so many issues, we don't want people stumbling with the wrong cython version.
=> chore(deps): bump cython to >= 3.0.5

src/zeroconf/_core.py, src/zeroconf/_handlers/answers.py, src/zeroconf/_handlers/multicast_outgoing_queue.py, src/zeroconf/_handlers/query_handler.pxd, src/zeroconf/_handlers/query_handler.py, src/zeroconf/_record_update.py, tests/test_handlers.py
Inspired by #1307
In most cases were won't be able to answer the questions because we don't have an answer in the ServiceRegistry for the question since we only know how to answer for entries we have. In this case we can avoid building a set of answers and parsing the known answers in the incoming packet in the majority of cases. 
**This is a significant speed up since parsing incoming packets is the most expensive thing zeroconf does.**
=> feat: avoid decoding known answers if we have no answers to give

bench/outgoing.py, src/zeroconf/_protocol/outgoing.pxd, src/zeroconf/_protocol/outgoing.py
- refactor the loop to only call `_has_more_to_add` once per loop when its a query
- add some more cython types
- cache common shorts
This is a ~22% speed up
=> feat: speed up outgoing packet writer

src/zeroconf/_cache.pxd, src/zeroconf/_dns.pxd, src/zeroconf/_dns.py, src/zeroconf/_handlers/query_handler.py, src/zeroconf/_handlers/record_manager.py, src/zeroconf/_history.pxd, src/zeroconf/_listener.py, src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py, src/zeroconf/_protocol/outgoing.py, src/zeroconf/_services/browser.pxd, src/zeroconf/_services/browser.py, src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py, tests/test_protocol.py
roughly a ~7% speed up for incoming
before: Parsing 100000 incoming messages took 2.558975583058782 seconds
after: Parsing 100000 incoming messages took 2.3616396670695394 seconds
roughly a ~2% speed up for outgoing (mostly a side effect)
before: Construction 100000 outgoing messages took 1.9390459168935195 seconds
after: Construction 100000 outgoing messages took 1.8946991249686107 seconds
=> feat: small speed up to processing incoming dns records

src/zeroconf/_dns.py, src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py
This is ~14% speed up
before: Parsing 100000 incoming messages took 2.3616396670695394 seconds
after: Parsing 100000 incoming messages took 2.012439667014405 seconds
=> feat: speed up incoming packet reader

src/zeroconf/_dns.pxd, src/zeroconf/_protocol/outgoing.pxd, src/zeroconf/_protocol/outgoing.py
This is ~ 6.5 % speed up
before: Construction 100000 outgoing messages took 1.9130162500077859 seconds
after: Construction 100000 outgoing messages took 1.7759123329306021 second
=> feat: small speed up to writing outgoing packets

bench/create_destory.py
Its recently come up that many consumers create and destroy zeroconf instances frequently because of their application design so create/destroy time is important.
It turns out most of the time is spent in `ifaddr`
https://github.com/pydron/ifaddr/pull/58 will reduce ipv6 related startup time
=> chore: add benchmark to create and destroy an instance

bench/txt_properties.py, src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py
This is ~43% speed up
before
Processing 100000 properties took 0.1892200000002049 seconds
after
Processing 100000 properties took 0.10781029199961267 seconds
=> feat: speed up unpacking TXT record data in ServiceInfo

examples/browser.py, src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py, tests/services/test_info.py
The scope_id was missing because it should come from the DNSAddress record and not the object itself if the ServiceInfo is pulling from the cache.  This also lead to duplicate IPv6 records being returned because the scope id was missing
fixes #1321
fixes #1288
scope_id only works on python 3.9+ since < 3.9 doesn't support it
=> fix: correct handling of IPv6 addresses with scope_id in ServiceInfo

src/zeroconf/_dns.py, tests/test_protocol.py
- The window and length should be been a single byte instead of a short per https://datatracker.ietf.org/doc/html/rfc3845#section-2.1.2
- Trying to convert an empty nsec record or one with an rdtype > 255 will now raise a `ValueError` to ensure we cannot write invalid records
dns python can parse the message now
```
>>> import dns.message
>>> dns.message.from_wire(b'\x00\x00\x80\x00\x00\x00\x00\x01\x00\x00\x00\x00\x13eufy HomeBase2-2464\x04_hap\x04_tcp\x05local\x00\x00/\x80\x01\x00\x00\x11\x94\x00\t\xc0\x0c\x00\x05\x00\x00\x80\x00@')
[<dns.wire.Parser object at 0x1029e2060>, 7]
[(0, b'\x00\x00\x80\x00@')]
<DNS message, ID 0>
```
This may be the issue above, or the issues below may be bugs in the mdns stacks that are consuming the NSEC records not allowing the name compression
fixes #1320 …
=> fix: correct nsec record writing

src/zeroconf/_services/info.pxd
aiohomekit and others use this for testing so we need to make it a cpdef
=> fix: re-expose ServiceInfo._set_properties for backwards compat

src/zeroconf/_utils/ipaddress.py, tests/utils/test_ipaddress.py
downstream calls this 1000-10000 times a minute
=> feat: cache is_unspecified for zeroconf ip address objects

src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py, tests/test_services.py
Clean up `ServiceInfo.properties` to always return `bytes`.
This is a technically breaking change. Its seems unlikely anyone is using it this way, but there is always someone. The type for the incoming `Dict` is missing which makes the interface unclear, and we ended up with a messy mix internally.  This PR aims to correct that. Adding the type would likely cause more pain so its not done in this PR
We continue to allow passing in properties as a mix of bytes and str with the type `Union[bytes, Dict[Union[str, bytes], Optional[Union[str, bytes]]]]`, but we will now convert any `str` to `bytes`
The typing on properties was very confusing because it could have a mix of bytes and str types, but only bytes would ever come back from the backend and cache. The only way str could happen is if …
=> feat: ensure ServiceInfo.properties always returns bytes

src/zeroconf/_utils/ipaddress.py
Instead of using the `__str__` cache on the object it was calling `__format__` which isn't optimized
=> fix: ensure IPv6 scoped address construction uses the string cache

src/zeroconf/_history.pxd, tests/test_history.py
There was a bug in the cython conversion logic that would loose precision on the float to double conversion
=> fix: ensure question history suppresses duplicates

src/zeroconf/_dns.pxd, src/zeroconf/_dns.py, tests/test_dns.py
Reverts python-zeroconf/python-zeroconf#1343
It turns out we don't need this
=> chore: partially revert add get_percentage_remaining_ttl helper to DNSRecord

src/zeroconf/_core.py, tests/test_asyncio.py
This has not been used anywhere in the code for a while
=> chore: remove deprecated handle_response

src/zeroconf/_core.py, src/zeroconf/_services/info.py, src/zeroconf/asyncio.py, tests/test_asyncio.py
Since the AsyncServiceBrowser will return a Zeroconf object, it was not obvious how to do an async lookup because only get_service_info was exposed on the Zeroconf object. async_get_service_info has been moved to the Zeroconf object, and AsyncZeroconf.async_get_service_info now wraps this method
related issue #1286
=> feat: make async_get_service_info available on the Zeroconf object

src/zeroconf/_utils/ipaddress.py, tests/utils/test_ipaddress.py
If the scope_id is 0 it should not be included in the IPv6Address object
fixes #1361
=> fix: avoid including scope_id in IPv6Address object if its zero

src/zeroconf/_handlers/record_manager.py, tests/test_handlers.py
An existing listener may add new listeners to process `ServiceInfo` when it sees a record (or for other reasons). We need to make a copy of the listeners set before iterating them to avoid `set changed size during iteration`
Fixes
```
2024-04-12 16:31:25.699 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 1248, in _read_ready
self._protocol.datagram_received(data, …
```
=> fix: set change during iteration when dispatching listeners

README.rst, pyproject.toml
Drop support for python3.7 as according to 4877829e6442de5426db152d11827b1ba85dbf59 and add explicit support for python3.12
=> fix: update references to minimum-supported python version of 3.8

src/zeroconf/_services/info.py
=> fix: improve helpfulness of ServiceInfo.request assertions

pyproject.toml
Poetry recommends the use of the official SPDX license expressions.
https://python-poetry.org/docs/pyproject/#license
Chose `LGPL-2.1-or-later` since that's referenced in the license headers.
https://github.com/python-zeroconf/python-zeroconf/blob/119122939ef0251b771bd5361ef17665331f7078/src/zeroconf/__init__.py#L7-L10
=> feat: use SPDX license identifier

.github/dependabot.yml
Just monthly to save resources.
fixes #1434
=> chore(dependabot): automatic Github Actions updates

tests/test_core.py
Python 3.8 is required, so no need for compatibility code.
=> chore(tests): remove outdated python 3.7 compatibility code

.pre-commit-config.yaml
Project requires python 3.8 so it should be used for `pyupgrade`.
No upgrade of the current code required.
=> chore(pre-commit): bump pyupgrade to required python 3.8

.github/workflows/ci.yml
Old pypy3.8 can be replaced with current pypy3.10.
=> chore(ci): increase tested pypy to 3.9 and 3.10

src/zeroconf/_dns.pxd, src/zeroconf/_dns.py, src/zeroconf/_protocol/incoming.pxd, src/zeroconf/_protocol/incoming.py
Most of the time parsing incoming records is spent in object creation. We can use cython's fast new path, and than use cdefs to create them which avoids all the type conversions.
=> feat: speed up parsing incoming records

.github/workflows/ci.yml
https://github.com/actions/runner-images/issues/10721
=> fix: move wheel builds to macos-13

src/zeroconf/_services/info.py, src/zeroconf/_utils/ipaddress.py, tests/services/test_info.py, tests/utils/test_ipaddress.py
Code for older python 3.9 is not required any more.
#1451
=> chore: remove legacy code <py39

src/zeroconf/_cache.pxd, src/zeroconf/_cache.py, tests/test_cache.py
This PR corrects a severe flaw in the cache design that was noticed while implementing https://github.com/python-zeroconf/python-zeroconf/pull/1465
The cache could return old stale records (incorrect created/ttls -- the contents of the record was correct) when the record was replaced in the underlying dict since the key is not updated (only the value is).
The following functions where affected:
`cache.async_entries_with_name`
`cache.async_entries_with_server`
`cache.async_all_by_details`
`cache.entries_with_name`
`cache.entries_with_server`
`cache.get_all_by_details`
`cache.get_by_details`
`cache.get` (never used)
Technically breaking change:
`async_entries_with_name` and `async_entries_with_server` now return a `list` instead of a `dict` which makes `entries_with_name` and …
=> fix: ensure cache does not return stale created and ttl values

tests/__init__.py
Naming was simplified with py3.9
Require py3.9 #1451
=> chore(tests): replace `lru_cache` with `cache`

src/zeroconf/_cache.pxd, src/zeroconf/_cache.py
Small performance improvement based on what was slow in the benchmark
- adds: avoid creating an empty dict
- expire: add some missing types to avoid some checks
=> feat: speed up adding and expiring records in the DNSCache

README.rst
Shows build status of documentation. May help to discover failing builds earlier than mentioned in #1494
.
=> chore: add badge for rtd build status

examples/resolve_address.py, src/zeroconf/__init__.py, src/zeroconf/_services/info.pxd, src/zeroconf/_services/info.py, tests/services/test_info.py
This pattern gets copied into a lot of downstream likes including `aioesphomeapi`, `esphome`, https://github.com/aio-libs/aiohttp-asyncmdnsresolver, etc
We can provide these as built-ins since its a common use case
```
(zeroconf-py3.12) bdraco@Mac python-zeroconf % python3 examples/resolve_address.py homeassistant.local.
DEBUG:asyncio:Using selector: KqueueSelector
homeassistant.local. IP addresses: [ZeroconfIPv4Address('192.168.x.x')]
(zeroconf-py3.12) bdraco@Mac python-zeroconf % 
```
=> feat: add simple address resolvers and examples

.pre-commit-config.yaml, pyproject.toml, src/zeroconf/_dns.py, src/zeroconf/_listener.py, src/zeroconf/_utils/net.py
- add types to `def _eq(self, other)`
- enable additional mypy checks
- `no_implicit_optional = true` is default since mypy v1 and could be removed.
=> chore: add typing, enable additional mypy checks

src/zeroconf/_utils/net.py
`ifaddr` didn't use to be typed until https://github.com/ifaddr/ifaddr/pull/53 so we can clean this up a bit now
=> chore: cleanup typing in net utils

docs/conf.py
- enable link to source code: 
- add some common default extensions
- fix rtd theme by adding missing extension
=> feat(docs): enable link to source code

src/zeroconf/_engine.py
https://docs.python.org/3/library/asyncio-task.html#creating-tasks
> Important Save a reference to the result of this function, to avoid a task disappearing mid-execution. The event loop only keeps weak references to tasks. A task that isn’t referenced elsewhere may get garbage collected at any time, even before it’s done. For reliable “fire-and-forget” background tasks, gather them in a collection:
=> fix: hold a strong reference to the AsyncEngine setup task

src/zeroconf/_utils/net.py, tests/utils/test_net.py
Create listener sockets when using unicast with specific IP version as well, just like in `new_respond_socket()`.
=> fix: create listener socket with specific IP version

src/zeroconf/_services/info.py, tests/services/test_info.py
Currently even when setting the explicit question type flag, the implementation ignores it for subsequent queries. This commit ensures that all queries respect the explicit question type flag.
=> fix: correctly override question type flag for requests

src/zeroconf/_utils/net.py, tests/utils/test_net.py
Load adapter list only once if operating in dual-stack mode. Also fix typing around adapater list to match what ifaddr defines.
=> fix: avoid loading adapter list twice

tests/utils/test_net.py
Make sure to close sockets after use. This fixes ResourceWarnings about unclosed sockets.
=> chore(test): fix resource warnings in test_net.py

src/zeroconf/_utils/net.py, tests/test_core.py, tests/utils/test_net.py
For IPv6, a shared listener/responder socket is not really possible when sending to link-local IPv6 multicast addresses (ff02::/16): The kernel needs to know which interface to use for routing.
On IPv4, this is historically a bit different, the kernel just uses what it deems the primary/best route interface based on the routing table. But for IPv6, a message is rejected by Linux with OSError no 99 "Cannot assign requested address" and OSError no 65 "No route to host" on macOS.
Removing the InterfaceChoice.Default config when IPv6 is enabled would be a major breaking change. Instead, inform the user with an error log message and a DeprecationWarning that this is not a working configuration.
As a further cleanup, move the socket options for sending multicast packets out of the common socket …
=> fix: address non-working socket configuration

src/zeroconf/_listener.pxd
Fix the few build failures I've hit with Cython 3.1.0rc1. Unfortunately, I'm stuck at:
```
Error compiling Cython file:
------------------------------------------------------------
...
version: IPVersion = IPVersion.All,
) -> list[DNSAddress]:
"""Return matching DNSAddress from ServiceInfo."""
return self._dns_addresses(override_ttl, version)
def _dns_addresses(
^
------------------------------------------------------------
src/zeroconf/_services/info.py:586:4: Signature not compatible with previous declaration
Error compiling Cython file:
------------------------------------------------------------
...
cpdef addresses_by_version(self, object version)
cpdef ip_addresses_by_version(self, object version)
@cython.locals(cacheable=cython.bint)
cdef cython.list _dns_addresses(self, object …
```
=> chore: some Cython 3.1.0rc1 build failures

src/zeroconf/_cache.pxd, src/zeroconf/_cache.py, src/zeroconf/_dns.pxd, src/zeroconf/_dns.py, src/zeroconf/_handlers/record_manager.pxd, src/zeroconf/_services/browser.py, src/zeroconf/const.py, tests/test_protocol.py
TTLs are always in full seconds. We shouldn't see any floats here.  This was legacy backwards compat, however they should all be fixed now.
Cython 3.1 compat
=> chore: migrate TTL to only accept int

tests/services/test_types.py
sometimes fails on GHA only with
```
FAILED tests/services/test_types.py::test_integration_with_listener_ipv6 - AssertionError: assert '_test-listenv6ip-type._tcp.local.' in ()
```
=> chore: disable flakey ipv6 test on github actions with macos

.github/workflows/ci.yml
windows-2019 is no longer available on GitHub, we need to build wheels with windows-latest
=> fix: missing wheel builds for Windows
