.gitignore
README.rst
setup.cfg
test_zeroconf.py
zeroconf.py

Add query support and test case for "_services._dns-sd._udp.local."

Find service types

---

test_zeroconf.py
zeroconf.py

This change validates service, instance and subtype names against [rfc6763](https://tools.ietf.org/html/rfc6763).
Also adds test code for same and for sub-types.
Also, by fixing name validation, provides a fix for issue #37.

Validate service names

---

test_zeroconf.py

added test for DNS-SD subtype discovery

---

test_zeroconf.py
zeroconf.py

Implement Name Compression for #66
Drop oversized packets in send as partial solution for #64
Add exception handler for oversized packets in receive

Help for oversized packets

---

test_zeroconf.py
zeroconf.py

This changes address #64, and by extension should address #62

Limit the size of the packet that can be built

---

test_zeroconf.py
zeroconf.py

Fix for #19 & #25.  This will stop the thread from crashing, but does not necessarily deal with the state of the socket.

Catch and log sendto() exceptions

---

zeroconf.py

fix an off by 1 error in packet creation when clipping over sized packets.

Simplify and fix PR 70

---

README.rst
test_zeroconf.py
zeroconf.py

Allow dots in service instance name

---

MANIFEST.in

Add license and readme file to source tarball

---

zeroconf.py

Implements support for outgoing unicast queries. See https://github.com/jstasiak/python-zeroconf/issues/121
This PR still needs tests.

implementing unicast support

---

zeroconf.py

On WSL (Windows 10 v1803 (17134.1)), some non relevant interfaces do not support `self._listen_socket.setsockopt(
socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP,
socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)`
This line make we gently ignore this error and continue to work properly.
Here is the output before:
```
(env) mdiez@Tiburaska:~/m/catt/x/python-zeroconf$ python self_test.py
Multicast DNS Service Discovery for Python, version 0.20.0
File "self_test.py", line 18, in <module>
r = Zeroconf()
File "/mnt/c/marcos/linux/catt/x/python-zeroconf/zeroconf.py", line 1710, in __init__
socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 22] Invalid argument
```
and after my fix:
```
(env) mdiez@Tiburaska:~/m/catt/x/python-zeroconf$ python …
```

Fix to make it work on WSL (Windows Service for Linux)

---

README.rst
zeroconf.py

Anticipating Travis build failure, #147 should fix that.

Spelling fixes

---

examples/browser.py
examples/registration.py
test_zeroconf.py
zeroconf.py

A follow up to 3d5787b8c5a92304b70c04f48dc7d5cec8d9aac8.

Rename IpVersion to IPVersion

---

zeroconf/__init__.py

The API is inspired by Apple's NetService.includesPeerToPeer
(see https://developer.apple.com/documentation/foundation/netservice/1414086-includespeertopeer)

Add support for AWDL interface on macOS

---

zeroconf/__init__.py
zeroconf/test.py

Initial commit to address
https://github.com/jstasiak/python-zeroconf/issues/163

Support cooperating responders

---

zeroconf/__init__.py

Zeroconf was eating up a bit more cpu time then expected with lots of devices on the network.
Reduce the number of calls to __eq__ when checking the cache as they are far more expensive than the 1000 second check.
Before
After

Optimize handle_response cache check

---

zeroconf/__init__.py

Iterating the cache is an expensive operation
when there is 100s of devices generating zeroconf
traffic as there can be 1000s of entries in the
cache.
Solves #246

Avoid iterating the entire cache when an A/AAAA entry is updated if the address has not changed.

---

zeroconf/__init__.py
zeroconf/test.py

To be merged only after #258 is merged and released.

Remove deprecated ServiceInfo address parameter/property

---

examples/browser.py

I had to fix some things manually, hence a separate PR.

Rebase PR 175

---

setup.py
zeroconf/__init__.py

https://github.com/jstasiak/python-zeroconf/issues/279

Use Adapter.index from ifaddr.

---

zeroconf/__init__.py

This improves Windows compatibility

Stop using socket.if_nameindex

---

zeroconf/__init__.py
zeroconf/test.py

Not asking already answered questions

---

zeroconf/__init__.py

Unfortunately, I'm still seeing what I think are instances of #255 on very busy networks.
This builds on #258 to only hold the lock if we have an update.
@mattsaxon Does this violate any of your assumptions ?

Reduce the time window that the handlers lock is held

---

zeroconf/__init__.py
zeroconf/test.py

Those really serve the same purpose -- are we receiving data (and want
to be flexible) or registering services (and want to be strict).

Merge strict and allow_underscores

---

zeroconf/__init__.py

Prevent crash when a service is added or removed during handle_response

---

docs/index.rst

I'm not overly familiar with sphinx, suspect this file may be auto-generated.

fix link to readme md --> rst

---

zeroconf/__init__.py

Cast listen_socket to socket.socket in create_sockets

---

zeroconf/__init__.py

- Reduce indentation with a return early guard in close

Return early when already closed

---

zeroconf/__init__.py
zeroconf/test.py

- Cache is now purged between reads when the interval is reached
- Reduce locking since we are already making a copy of the readers
and not reading under the lock

Eliminate the reaper thread

---

zeroconf/__init__.py
zeroconf/test.py

Provides a `load_from_cache` method on ServiceInfo that does no I/O
- When a ServiceBrowser is running for a type there is no need
to make queries on the network since the entries will already
be in the cache. When discovering many devices making queries
that will almost certainly fail for offline devices delays the
startup of online devices.
- The DNSEntry and ServiceInfo classes were matching on the name
instead of the key (lowercase name). These classes now treat dns
names the same reguardless of case.
https://datatracker.ietf.org/doc/html/rfc6762#section-16
> The simple rules for case-insensitivity in Unicast DNS [RFC1034]
> [RFC1035] also apply in Multicast DNS; that is to say, in name
> comparisons, the lowercase letters "a" to "z" (0x61 to 0x7A) match
> their uppercase equivalents …

Separate cache loading from I/O in ServiceInfo

---

zeroconf/asyncio.py
zeroconf/test_asyncio.py

The tasks scheduled by `async_register_service`, `async_unregister_service` and `async_update_service` are lost and can never be awaited.
Returning the result of `asyncio.ensure_future` (a Task object in this case) will provide access to the broadcast tasks, but not force them to be awaited.
The test added is a direct copy of `test_async_service_registration`, except it awaits the broadcast tasks instead of sleeping for the expected duration.

Return task objects created by AsyncZeroconf

---

zeroconf/test.py
zeroconf/test_asyncio.py

Wrote these to validate https://github.com/home-assistant/core/issues/50695

Improve test coverage for name conflicts

---

zeroconf/test_asyncio.py

- Await the awaitables added in #360 instead of using asyncio.sleep

Small cleanups to asyncio tests

---

zeroconf/__init__.py

- Return as record is not viable (None or expired)
- Switch checks to isinstance since its needed by mypy anyways
- Prepares for supporting multiple AAAA records (via https://github.com/jstasiak/python-zeroconf/pull/361)

Small cleanup of ServiceInfo.update_record

---

pyproject.toml
zeroconf/__init__.py

- The issue that prevented black from being used on this
block was resolved in https://github.com/psf/black/pull/763

Remove black python 3.5 exception block

---

zeroconf/__init__.py

- Use get_all_by_details to ensure all records are loaded
into addresses.
- Only load A/AAAA records from cache once in load_from_cache
if there is a SRV record present
- Move duplicate code that checked if the ServiceInfo was complete
into its own function

Ensure ServiceInfo populates all AAAA records

---

zeroconf/__init__.py

- add_answer_at_time was always called with None
since it was only added to the outgoing request
when the cached_entry returned None (appears to have been introduced in #292)
- Avoid populating ServiceInfo from cache when
adding the listener to do the request since
it was just done in load_from_cache
- Reduce duplicate code in ServiceInfo.request
by moving blocks into DNSOutgoing

Fix empty answers being added in ServiceInfo.request

---

zeroconf/__init__.py
zeroconf/test.py

- Ensure we only evict records with the same name, rrtype, and rrclass when
we recieve a cache flush request

Fix RFC6762 Section 10.2 paragraph 2 compliance

---

zeroconf/__init__.py

- With multiple types, the ServiceBrowser questions can be
chatty because it would generate a question packet for
each type. If multiple types are due to be requested,
try to combine the questions into a single outgoing
packet(s)

Coalesce browser questions scheduled at the same time

---

zeroconf/test.py

Addresses intermittent CI failures

Fix multiple unclosed instances in tests

---

zeroconf/asyncio.py

- The check was not happening after the last query

Ensure the cache is checked for name conflict after final service query with asyncio

---

zeroconf/__init__.py

- Eliminates the try catch by replacing the dict lookup that
can fail with a .get

Simplify DNSPointer processing in ServiceBrowser

---

zeroconf/test.py

Followup to add coverage for #366 now that the CI can do IPv6

Add test coverage for multiple AAAA records

---

zeroconf/__init__.py

Remove unreachable code in ServiceInfo

---

zeroconf/__init__.py

- Will be used to send the query in asyncio

Seperate query generation in ServiceInfo

---

zeroconf/__init__.py

- Will be used to send the query in asyncio

Seperate query generation for Zeroconf

---

zeroconf/asyncio.py

- Sends now go into a queue and are processed by the thread FIFO
- Avoids overwhelming the executor when registering multiple
services in parallel
Fixes https://github.com/jstasiak/python-zeroconf/issues/396

Use a dedicated thread for sending outgoing packets with asyncio

---

zeroconf/__init__.py
zeroconf/test.py

- Notify listeners will be used by AsyncZeroconf to set
asyncio.Event objects when new data is received
- Registering a notify listener:
notify_listener = YourNotifyListener()
Use zeroconf.add_notify_listener(notify_listener)
- Unregistering a notify listener:
Use zeroconf.remove_notify_listener(notify_listener)
- Notify listeners must inherit from the NotifyListener
class

Add support for registering notify listeners

---

zeroconf/asyncio.py
zeroconf/test_asyncio.py

- Mirrors the .wait function in Zeroconf

Add async_wait function to AsyncZeroconf

---

zeroconf/asyncio.py
zeroconf/test_asyncio.py

- These functions are the async equivalent of Zeroconf.get_service_info and
ServiceInfo.request
Example usage for parallel lookups:
```python
DEVICE = ("device1", "device2", "device3"):
TYPE = "_hap._tcp.local."
service_infos = [AsyncServiceInfo(TYPE, f"{device}.{TYPE}") for device in DEVICES]
await asyncio.gather(*[s.async_request(aiozc, 3000) for s in service_infos])
```

Add async_get_service_info to AsyncZeroconf and async_request to AsyncServiceInfo

---

examples/async_registration.py

Add async_register_service/async_unregister_service example

---

examples/async_service_info_request.py

Add async_request example with browse

---

zeroconf/__init__.py

Seperate query generation for ServiceBrowser

---

zeroconf/__init__.py

- Prepares for the change from update_record to update_records in #419

Seperate logic for consuming records in ServiceInfo

---

zeroconf/__init__.py

A methods to generate DNSRecords from ServiceInfo

---

zeroconf/__init__.py

- This should always return all addresses since its _CLASS_UNIQUE

Remove unused argument from ServiceInfo.dns_addresses

---

zeroconf/__init__.py

- _services._dns-sd._udp.local. is a special case and should never
be in the registry
Fixes #424

Avoid checking the registry when answering requests for _services._dns-sd._udp.local.

---

zeroconf/__init__.py

- _ServiceBrowserBase can be used for asyncio without threading

Seperate non-thread specific code from ServiceBrowser into _ServiceBrowserBase

---

docs/api.rst

Add zeroconf.asyncio to the docs

---

zeroconf/__init__.py

There are a lot less of these now, but some of these are going to be hard to get rid of.

Disable broad except checks in places we still catch broad exceptions

---

zeroconf/asyncio.py

* pylint: Method could be a function (no-self-use)

Extract _get_queue from _AsyncSender

---

Makefile
pyproject.toml
requirements-dev.txt
zeroconf/asyncio.py

- Disable dupe code check since asyncio will always have some dupes
- Add pylint to requirements

Enable pylint

---

zeroconf/__init__.py

First pass at https://github.com/jstasiak/python-zeroconf/issues/458

Reduce branching in Zeroconf.handle_query

---

zeroconf/__init__.py

Reduce branching in Zeroconf.handle_response

---

zeroconf/__init__.py

Will break out this branch to reduce branching to get closer to closing #458

Use constant for service type enumeration

---

zeroconf/__init__.py
zeroconf/test.py

Ensure PTR questions asked in uppercase are answered

---

zeroconf/test.py

Fix flakey test_update_record

---

zeroconf/__init__.py
zeroconf/test.py

- Adds `update_records` method to `ServiceInfo`
Breakout of #419

Add support for updating multiple records at once to ServiceInfo

---

zeroconf/__init__.py
zeroconf/asyncio.py

Avoid the magic number that led to the bug in https://github.com/jstasiak/python-zeroconf/pull/480

Provide a helper function to convert milliseconds to seconds

---

zeroconf/__init__.py

- There was a short race condition window where the ServiceBrowser
could add to _handlers_to_call in the Engine thread, have the
condition notify_all called, but since the ServiceBrowser was
not yet holding the condition it would not know to stop waiting
and process the handlers to call.
Fixes #476 for sync, ~~#478 is the fix for async~~
Fixes #471

ServiceBrowser must recheck for handlers to call when holding condition

---

zeroconf/asyncio.py

- Using a asyncio.Condition permits fixing a race condition
in processing handlers similar to the sync version in #477

Switch from using an asyncio.Event to asyncio.Condition for waiting

---

zeroconf/__init__.py

- Eliminate the need to duplicate code between the ServiceBrowser
and AsyncServiceBrowser to calculate the wait time.

Relocate ServiceBrowser wait time calculation to seperate function

---

zeroconf/asyncio.py

- There was a short race condition window where the AsyncServiceBrowser
could add to _handlers_to_call in the Engine thread, have the
condition notify_all called, but since the AsyncServiceBrowser was
not yet holding the condition it would not know to stop waiting
and process the handlers to call.
Fixes #476 for async, #477 is the fix for sync
Fixes #471

AsyncServiceBrowser must recheck for handlers to call when holding condition

---

examples/async_browser.py

Add AsyncServiceBrowser example

---

zeroconf/__init__.py

Remove unused __ne__ code from Python 2 era

---

zeroconf/__init__.py

Update internal version check to match docs (3.6+)

---

zeroconf/__init__.py
zeroconf/test.py

- Ensure that questions that exceed the max packet size are
moved to the next packet. This fixes DNSQuestions being
sent in multiple packets in violation of:
https://datatracker.ietf.org/doc/html/rfc6762#section-7.2
Fixes #496 and Fixes #495
- Ensure only one resource record is sent when a record
exceeds _MAX_MSG_TYPICAL
https://datatracker.ietf.org/doc/html/rfc6762#section-17

Ensure packets are properly seperated when exceeding maximum size

---

zeroconf/__init__.py
zeroconf/test.py

https://datatracker.ietf.org/doc/html/rfc6762#section-7.2
```
Sometimes a Multicast DNS querier will already have too many answers
to fit in the Known-Answer Section of its query packets.  In this
case, it should issue a Multicast DNS query containing a question and
as many Known-Answer records as will fit.  It MUST then set the TC
(Truncated) bit in the header before sending the query.  It MUST
immediately follow the packet with another query packet containing no
questions and as many more Known-Answer records as will fit.  If
there are still too many records remaining to fit in the packet, it
again sets the TC bit and continues until all the Known-Answer
records have been sent.
```
Fixes #493

Set the TC bit for query packets where the known answers span multiple packets

---

zeroconf/__init__.py

Extract code for handling queries into QueryHandler

---

zeroconf/test.py

Supports #505
There are still a few more to cleanup

Stop monkey patching send in the PTR optimization test

---

zeroconf/test.py

This test was actually failing but since the assertions were happening in another thread they were not seen. The failures were showing as uncaught thread exceptions in the CI but they were not seen as fatal.
Supports #505

Stop monkey patching send in the TTL test

---

zeroconf/__init__.py

- records could only be set if there were questions

Small cleanups to RecordManager.add_listener

---

zeroconf/__init__.py
zeroconf/test.py

Move ipversion auto detection code into its own function

---

zeroconf/__init__.py
zeroconf/const.py

Move constants into const.py

---

zeroconf/__init__.py
zeroconf/exceptions.py

Move exceptions into zeroconf.exceptions

---

zeroconf/__init__.py
zeroconf/logger.py

Move logger into zeroconf.logger

---

zeroconf/__init__.py

- This is not a breaking change since this code has not
yet shipped

Avoid making DNSOutgoing aware of the Zeroconf object

---

zeroconf/__init__.py
zeroconf/aio.py
zeroconf/utils/net.py

Breakout network utils into zeroconf.utils.net

---

zeroconf/__init__.py
zeroconf/services.py

- This is not a breaking change since it was never released
in the utils module
Fixes #545

Move ServiceStateChange to zeroconf.services

---

zeroconf/core.py
zeroconf/handlers.py

Supports https://github.com/jstasiak/python-zeroconf/issues/521

Move QueryHandler and RecordManager handlers into zeroconf.handlers

---

zeroconf/__init__.py
zeroconf/services/types.py

Move ZeroconfServiceTypes to zeroconf.services.types

---

tests/utils/test_net.py

Add missing coverage for ipv6 network utils

---

zeroconf/__init__.py
zeroconf/cache.py
zeroconf/core.py
zeroconf/dns.py

Breakout DNSCache into zeroconf.cache

---

tests/services/__init__.py
tests/services/test_types.py
tests/test_init.py

Relocate ServiceTypesQuery tests to tests/services/test_types

---

tests/test_dns.py
zeroconf/_dns.py

Needed to fix https://github.com/jstasiak/python-zeroconf/issues/500

Add unicast property to DNSQuestion to determine if the QU bit is set

---

tests/test_handlers.py
zeroconf/_core.py
zeroconf/_handlers.py

- Unicast responses were only being sent if the source port
was 53, this prevented responses when testing with dig:
dig -p 5353 @224.0.0.251 media-12.local
The above query will now see a response since
Fixes #594

Ensure unicast responses can be sent to any source port

---

zeroconf/_core.py

Log destination when sending packets

---

tests/test_core.py
tests/test_dns.py
zeroconf/_core.py
zeroconf/_dns.py

- The bit should be set per
https://datatracker.ietf.org/doc/html/rfc6762#section-8.1

Ensure the QU bit is set for probe queries

---

tests/test_handlers.py
zeroconf/_handlers.py

Fix queries for AAAA records

---

tests/test_handlers.py
zeroconf/_handlers.py

Suppress additionals when they are already in the answers section

---

tests/test_handlers.py
zeroconf/_handlers.py

Ensure matching PTR queries are returned with the ANY query

---

tests/test_handlers.py
zeroconf/_core.py
zeroconf/_handlers.py

- Implements RFC6762 sec 14
https://datatracker.ietf.org/doc/html/rfc6762#section-14
Closes #395

Protect the network against excessive packet flooding

---

tests/test_handlers.py
zeroconf/_handlers.py

- Implements RFC 6762 sec 5.4:
Questions Requesting Unicast Responses
https://datatracker.ietf.org/doc/html/rfc6762#section-5.4
closes #500

Add support for handling QU questions

---

zeroconf/const.py

Ensure zeroconf can be loaded when the system disables IPv6

---

tests/test_init.py
tests/test_services.py

Add test to ensure ServiceBrowser sees port change as an update

---

tests/test_core.py
tests/test_dns.py
zeroconf/_core.py

- Improve coverage for handling invalid incoming data

Return early on invalid data received

---

zeroconf/_core.py

- Return as soon as possible during close/shutdown

Return early in the shutdown/close process

---

zeroconf/_dns.py

- These functions are not intended to be used by external
callers and the API is not likely to be stable in the future

Mark DNSOutgoing write functions as protected

---

zeroconf/_core.py

- Prevent ConnectionResetError from being thrown on
Windows with ProactorEventLoop on cpython 3.8+

Ensure eventloop shutdown is threadsafe

---

zeroconf/_core.py
zeroconf/aio.py

- async_close no longer generates an executor job

Remove all calls to the executor in AsyncZeroconf

---

tests/test_aio.py
zeroconf/aio.py

Add an AsyncZeroconfServiceTypes to mirror ZeroconfServiceTypes to zeroconf.aio

---

tests/test_core.py

Add oversized packet to the invalid packet test

---

zeroconf/_dns.py

- Most of the time we only check one of the time attrs
or none at all. Wait to calculate them until they are
requested.
cloes #673

Make calculation of times in DNSRecord lazy

---

zeroconf/_handlers.py

- DNSRRSet uses hash table lookups under the hood which
is much faster than the linear searches used by
DNSRecord.suppressed_by
Closes https://github.com/jstasiak/python-zeroconf/issues/672

Use DNSRRSet for known answer suppression

---

tests/services/test_types.py
tests/test_core.py
tests/test_handlers.py
zeroconf/_core.py
zeroconf/_handlers.py

- Implements https://datatracker.ietf.org/doc/html/rfc6762#section-7.2
- Fixes https://github.com/jstasiak/python-zeroconf/issues/499

Implement multi-packet known answer supression

---

zeroconf/_dns.py

- Not intended for public use, only for mocking in tests

Move setting DNS created and ttl into its own function

---

zeroconf/_dns.py

Supports https://github.com/jstasiak/python-zeroconf/issues/691

Abstract DNSOutgoing ttl write into _write_ttl

---

zeroconf/_services/__init__.py

Fix thread safety in _ServiceBrowser.update_records_complete

---

zeroconf/_core.py

ref https://github.com/python/mypy/issues/1178

Cleanup typing in zero._core and document ignores

---

zeroconf/_handlers.py

Followup to #709 for missed locations

Synchronize time for fate sharing

---

tests/test_services.py
zeroconf/_services/__init__.py

- Add coverage for the handler from listener

Breakout ServiceBrowser handler from listener creation

---

Makefile
requirements-dev.txt

- When debugging, the failure to timeout was blocking
all CI runs

Add 60s timeout for each test

---

tests/test_init.py

- This was testing two things: name changes and log handling
- Now test_verify_name_change_with_lots_of_names and
test_large_packet_exception_log_handling
This test was failing occasionally on pypy3 mac os only
and the CI did not give enough to understand what was going
wrong. Next time it fails we will get a better idea where.

Break test_lots_of_names into two tests

---

tests/test_handlers.py
zeroconf/_handlers.py

Add test coverage to ensure RecordManager.add_listener callsback known question answers

---

tests/services/test_browser.py
zeroconf/_services/browser.py

Implement accidental synchronization protection (RFC2762 section 5.2)

---

tests/test_handlers.py

- This file did not seem to trip the block check for some
reason

Reformat test_handlers

---

zeroconf/_protocol.py

After reviewing more callgrind files, this seems like a better solution (and simpler) and since its only used in one place and it just wrapping `str`, it was a bit much anyways.
closes #766 (round 2)
replaces reverts https://github.com/jstasiak/python-zeroconf/pull/781 and https://github.com/jstasiak/python-zeroconf/pull/779

Inline utf8 decoding when processing incoming packets

---

tests/test_aio.py
zeroconf/_services/info.py

Add a guard to prevent running ServiceInfo.request in async context

---

tests/services/test_browser.py
zeroconf/_core.py
zeroconf/_handlers.py
zeroconf/_services/browser.py
zeroconf/_services/info.py
zeroconf/aio.py

These functions added and removed lists that would be iterated in different threads.

Make add_listener and remove_listener threadsafe

---

tests/test_core.py
tests/utils/test_aio.py
zeroconf/_utils/aio.py

Ensure we handle threadsafe shutdown under PyPy with multiple event loops

---

zeroconf/_utils/aio.py

- This function always did the same thing on timeout and
wait complete so we can use the same callback.  This
solves the CI failing due to the test coverage flapping
back and forth as the timeout would rarely happen.
Fixes the partial in the CI https://codecov.io/gh/jstasiak/python-zeroconf/src/0129ac061db4a950f7bddf1084309e44aaabdbdf/zeroconf/_utils/aio.py

Simplify wait_event_or_timeout

---

tests/services/test_types.py

- Will be needed to track down #813

Turn on logging in the types test

---

tests/services/test_browser.py
tests/services/test_info.py

Fix default v6_flow_scope argument with tests that mock send

---

tests/__init__.py
tests/services/test_browser.py

These tests were patching before everything was up and running.
Closes #815

Fix reliablity of tests that patch sending

---

tests/test_handlers.py

Fix thread safety in handlers test

---

tests/__init__.py
tests/test_init.py

Speed up test_verify_name_change_with_lots_of_names under PyPy

---

tests/services/test_info.py

This was the only non-covered line in `info.py`

Add test coverage for duplicate properties in a TXT record

---

tests/test_services.py

Fixes https://github.com/jstasiak/python-zeroconf/pull/875/checks?check_run_id=2937859078

Fix flapping test test_integration_with_listener_class

---

tests/utils/test_net.py
zeroconf/_utils/net.py

Break apart net_socket for easier testing

---

tests/utils/test_net.py

Adds coverage for #327
Closes #872

Add coverge for disconnected adapters in add_multicast_member

---

.github/workflows/ci.yml

Disable pylint in the CI

---

README.rst

- Remove internal refactoring information from public changelog
Closes #882 Closes #881

Collapse changelog for 0.32.0

---

README.rst

Rewrite 0.32.0 changelog in past tense

---

zeroconf/_core.py
zeroconf/_utils/asyncio.py
zeroconf/asyncio.py

Reduce duplicate code between zeroconf.asyncio and zeroconf._core

---

tests/test_asyncio.py
tests/test_dns.py
tests/test_protocol.py
zeroconf/__init__.py
zeroconf/_dns.py
zeroconf/_protocol.py
zeroconf/const.py

- This is needed for negative responses
https://datatracker.ietf.org/doc/html/rfc6762#section-6.1
Supports #897

Implement NSEC record parsing

---

tests/test_protocol.py
zeroconf/_dns.py

Rename DNSNsec.next to DNSNsec.next_name

---

zeroconf/_core.py

- Switch to using run_coro_with_timeout from sync context
- A safe-guard has been added to close to prevent blocking
the event loop when Zeroconf.close is called from asyncio
as unregister_all_services is a blocking operation (and
always has been)

Remove duplicate unregister_all_services code

---

tests/test_core.py
zeroconf/_core.py

- Simplifies AsyncEngine to avoid the long running
task

Switch periodic cleanup task to call_later

---

README.rst

- Fixes overly restrictive directory permissions reported in #923
fixes #923

Update changelog for 0.33.1

---

zeroconf/_dns.py
zeroconf/_handlers.py
zeroconf/_logger.py
zeroconf/_protocol.py
zeroconf/_services/__init__.py
zeroconf/_services/browser.py
zeroconf/_services/info.py
zeroconf/_updates.py
zeroconf/_utils/net.py

Remove some pylint workarounds

---

zeroconf/_core.py

- Fixes a typo in handle_assembled_query that prevented immediate
responses from being sent.

Fix sending immediate multicast responses

---

tests/services/test_info.py
zeroconf/_services/info.py

- ServiceInfo requests are frequently triggered by multicast responses
to ServiceBrowser requests.  When multiple instances of zeroconf are
present on the same network, they can all end up sending ServiceInfo
queries at the same time.  We now use a random delay as described in
rfc6762 sec 5.2 after the first request.  Ideally we would add the
delay before the first query as well, however that may break existing
workflows so it was not done at this time.
Fixes #897

Reduce chance of accidental synchronization of ServiceInfo requests

---

zeroconf/_protocol.py

- Small cleanups to this class
- Reduces memory pressure on large networks

Reduce dns protocol attributes and add slots

---

zeroconf/_core.py

- Breakout functions without self-use

Remove unused code in zeroconf._core

---

tests/__init__.py

Fix test failure when has_working_ipv6 generates an exception

---

tests/test_logger.py
zeroconf/_logger.py
zeroconf/_protocol/incoming.py

- Warning about network traffic we have no control over
is confusing to users as they think there is
something wrong with zeroconf
References https://github.com/home-assistant/core/issues/59415

Downgrade incoming corrupt packet logging to debug

---

tests/test_asyncio.py
zeroconf/_handlers.py
zeroconf/_services/browser.py

- Avoid fetching time again between updates

Improve performance of query scheduler

---

zeroconf/_protocol/incoming.py

Make decode errors more helpful in finding the source of the bad data

---

tests/test_asyncio.py
tests/test_dns.py
zeroconf/_cache.py
zeroconf/_dns.py

Fix IP Address updates when hostname is uppercase

---

Makefile
zeroconf/_protocol/incoming.py
zeroconf/asyncio.py

Update stale docstrings in AsyncZeroconf

---

tests/utils/test_asyncio.py

Fix run_coro_with_timeout test not running in the CI

---

zeroconf/_protocol/outgoing.py

Small performance improvement for sending outgoing data

Replace pack with to_bytes

---

zeroconf/_services/info.py

We should only callback all the address records in the cache
to _process_record_threadsafe if the server has changed

Only reprocess address records if the server changes

---

.github/workflows/ci.yml

temporary set the upload urls to the test.pypi.org

chore: additional release automation prep

---

.github/workflows/ci.yml
pyproject.toml

There should not be a `v` prefix

chore: fix ciwheel build tags

---

src/zeroconf/_protocol/incoming.py

feat: optimize incoming parser by using unpack_from

---

src/zeroconf/_dns.pxd
tests/services/test_browser.py

This will help with the object construction and throw away when we suppress the response in the handlers.

feat: optimize dns objects by adding pxd files

---

src/zeroconf/_dns.pxd
src/zeroconf/_dns.py
src/zeroconf/_handlers.py
src/zeroconf/_protocol/incoming.py
tests/test_dns.py

reduce DNSRRSet construction overhead

feat: improve performance of processing incoming records

---

src/zeroconf/_handlers.py

There were a few casts in hot paths that should have been guarded with if TYPE_CHECKING

fix: small internal typing cleanups

---

src/zeroconf/_dns.pxd
src/zeroconf/_dns.py
src/zeroconf/_handlers.py

Speeds up the construction of the DNSRRSet lookup

feat: speed up answering incoming questions

---

src/zeroconf/_core.py

Unpacks the address only after we know we are going to process the incoming message

feat: reorder incoming data handler to reduce overhead

---

src/zeroconf/_cache.py
src/zeroconf/_protocol/incoming.py
src/zeroconf/_protocol/outgoing.py

Hide a few more types to prevent them from being cythonized where we want them to stay native py objects
closes #1183

feat: cython3 support

---

src/zeroconf/_dns.pxd
src/zeroconf/_dns.py

add cython defs for dns record ttl compares

feat: speed up processing incoming records

---

src/zeroconf/_core.py
src/zeroconf/_services/info.py
src/zeroconf/asyncio.py
tests/test_asyncio.py
tests/utils/test_name.py

feat: expose flag to disable strict name checking in service registration

---

src/zeroconf/_core.py
src/zeroconf/_engine.py
tests/conftest.py
tests/services/test_browser.py
tests/test_core.py
tests/test_engine.py
tests/utils/test_asyncio.py

cython implementation for _engine.py in the next PR

chore: split AsyncEngine into _engine.py

---

build_ext.py
tests/test_core.py

No pxd file yet. This will be the next PR. Doing this in small steps

feat: cythonize _listener.py to improve incoming message processing performance

---

src/zeroconf/_handlers.py

Avoids construction of the lambda on each response, uses attrgetter which is pre-built

feat: optimizing sending answers to questions

---

src/zeroconf/_services/info.py

This is one of most common operations from discovery so anything we can do to improve the performance here is a win.
We may need to cython

feat: simplify code to unpack properties

---

src/zeroconf/_handlers/query_handler.py

- only build known_answers_set once per question set
- remove unused variables and code paths
- unpack functions only called in one place

feat: reduce overhead to answer questions

---

src/zeroconf/_cache.pxd
src/zeroconf/_cache.py
src/zeroconf/_handlers/record_manager.py

Remove itertools usage since it was not needed

feat: optimize cache implementation

---

build_ext.py
src/zeroconf/_handlers/query_handler.pxd
src/zeroconf/_handlers/query_handler.py
src/zeroconf/_history.pxd
src/zeroconf/_services/registry.pxd

adds a cython pxd for query_handler.py

feat: speed up answering queries

---

src/zeroconf/_protocol/incoming.pxd
src/zeroconf/_protocol/incoming.py

This is roughly a 8.6% speed up

feat: speed up decoding incoming packets

---

src/zeroconf/_protocol/outgoing.pxd
src/zeroconf/_protocol/outgoing.py

This is only ~3% but opens the door for the next PR which will make much more difference

feat: small speed up to writing outgoing dns records

---

src/zeroconf/_handlers/query_handler.pxd
src/zeroconf/_handlers/query_handler.py
src/zeroconf/_services/info.pxd
src/zeroconf/_services/info.py
src/zeroconf/_services/registry.pxd
tests/services/test_info.py

- Adds cdefs for all ServiceInfo record generators

feat: speed up answering questions

---

src/zeroconf/_dns.pxd
src/zeroconf/_dns.py
src/zeroconf/_handlers/query_handler.pxd
src/zeroconf/_handlers/query_handler.py

feat: speed up responding to queries

---

src/zeroconf/_handlers/answers.pxd
src/zeroconf/_handlers/answers.py
src/zeroconf/_protocol/outgoing.pxd
src/zeroconf/_protocol/outgoing.py

Construction 100000 outgoing messages took 2.71892695799761 seconds

feat: improve performance of constructing outgoing queries

---

src/zeroconf/_services/browser.pxd

Missed one function on the last PR

feat: small speed ups to ServiceBrowser

---

src/zeroconf/_dns.pxd
src/zeroconf/_handlers/query_handler.pxd
src/zeroconf/_handlers/query_handler.py
src/zeroconf/_handlers/record_manager.pxd
src/zeroconf/_handlers/record_manager.py

- remove dead code
- add explict checks for truth
- add more cython typing

feat: small cleanups to incoming data handlers

---

src/zeroconf/_services/browser.pxd
src/zeroconf/_services/browser.py

Adds cython typing for processing incoming DNSPointer records

feat: small improvements to ServiceBrowser performance

---

src/zeroconf/_services/browser.pxd
src/zeroconf/_services/browser.py
tests/services/test_browser.py

#1292 introduced a regression in browser that made it unable to be cythonized

chore: fix cythonize of browser

---

src/zeroconf/_services/browser.py
tests/test_asyncio.py

There are still more failing, but this fixes a few more

chore: fix more failing ServiceBrowser tests

---

src/zeroconf/_protocol/incoming.pxd

- adds cython typing to the label decode function

feat: speed up decoding labels from incoming data

---

src/zeroconf/_core.py
src/zeroconf/_listener.pxd
src/zeroconf/_listener.py

- drop some kwargs to normal args that are always there now
- add some typing for the fast path

feat: small speed up to process incoming packets

---

src/zeroconf/_services/browser.pxd
src/zeroconf/_services/browser.py
tests/services/test_browser.py

- add some more cython typing to the service browser

feat: speed up service browser queries when browsing many types

---

bench/outgoing.py
src/zeroconf/_protocol/outgoing.pxd
src/zeroconf/_protocol/outgoing.py

feat: speed up writing name compression for outgoing packets

---

build_ext.py
src/zeroconf/_services/info.pxd
src/zeroconf/_services/info.py
src/zeroconf/_utils/ipaddress.pxd
src/zeroconf/_utils/ipaddress.py
tests/utils/test_ipaddress.py

https://github.com/python-zeroconf/python-zeroconf/pull/1322 introduced a performance regression with IPv6 addresses
fixes #1329

fix: performance regression with ServiceInfo IPv6Addresses

---

src/zeroconf/_dns.pxd
src/zeroconf/_dns.py
tests/test_dns.py

This is an internal helper to support #1335

chore: add get_percentage_remaining_ttl helper to DNSRecord

---

src/zeroconf/_services/browser.pxd
src/zeroconf/_services/info.pxd
src/zeroconf/_updates.pxd

adds missing void types to update functions

feat: small speed up to processing incoming records

---

src/zeroconf/_cache.pxd
src/zeroconf/_core.py
src/zeroconf/_handlers/answers.pxd
src/zeroconf/_handlers/multicast_outgoing_queue.pxd
src/zeroconf/_handlers/query_handler.pxd
src/zeroconf/_handlers/query_handler.py
src/zeroconf/_protocol/incoming.pxd

refactor the query handler and add additional types to related modules

feat: speed up processing incoming packets

---

.github/workflows/ci.yml

fix: bump cibuildwheel to fix wheel builds

---

src/zeroconf/_services/info.py
src/zeroconf/_utils/ipaddress.py
tests/services/test_info.py

We end up spending a lot of time in the ip address object __eq__ when there are a long list of addresses

feat: improve performance when IP addresses change frequently

---

src/zeroconf/_cache.pxd
src/zeroconf/_cache.py

feat: improve performance of DNSCache backend

---

src/zeroconf/_cache.py
src/zeroconf/_core.py
src/zeroconf/_handlers/query_handler.py
src/zeroconf/_handlers/record_manager.py
src/zeroconf/_listener.py
src/zeroconf/_protocol/incoming.py
src/zeroconf/_services/info.py
src/zeroconf/_utils/time.py

Just typos in documentation corrected. No code change.

fix: correct typos

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml
tests/services/test_browser.py
tests/services/test_info.py
tests/test_asyncio.py
tests/test_core.py
tests/test_handlers.py
tests/test_protocol.py

* feat(pre-commit): reenable codespell and disable false positives
* fix(docs): correct typos

chore(pre-commit): reenable codespell and disable false positives 

---

.github/workflows/ci.yml

fix(ci): run release workflow only on main repository

---

.pre-commit-config.yaml

* remove duplicated hook
* sort hooks alphabetically

chore(pre-commit): remove duplicated hook

---

.readthedocs.yaml

I'm not sure if it solves the problem completely, but it's a starting point.
fixes #1494

chore(docs): add readthedocs config

---

.pre-commit-config.yaml

... to improve performance
fixes #1449

chore: limit `prettier` to specific files

---

.pre-commit-config.yaml
pyproject.toml
src/zeroconf/_cache.py
src/zeroconf/_core.py
src/zeroconf/_handlers/answers.py
src/zeroconf/_listener.py
src/zeroconf/_protocol/outgoing.py
src/zeroconf/_services/browser.py
src/zeroconf/_services/info.py
src/zeroconf/_utils/asyncio.py
src/zeroconf/_utils/net.py
src/zeroconf/asyncio.py
tests/conftest.py
tests/test_init.py
tests/test_listener.py
tests/test_logger.py
tests/utils/test_net.py

- update to modern typing
- increase target python version to 3.9 for lint tools
followup to #1502

chore: update to modern typing

---

.github/workflows/ci.yml

feat: add armv7l wheel builds

---

.github/workflows/ci.yml

chore: split up armv7l wheels to speed up release

---

src/zeroconf/_utils/net.py
tests/utils/test_net.py

fix: add a helpful hint for when EADDRINUSE happens during startup

---

.github/workflows/ci.yml

chore: update process to get relase tag from PSR in release workflow
